### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by NJnisarg** [WebClub-NITK/Hacktoberfest-2k19#1]
### Description
Introducing yourself on the repo. Create a file as `yourname.txt` with details about yourself and submit it for a PR. This is supposed to be a good first issue.

### Details
- Technical Specifications:
- Type of issue: Single
- Time Limit: No bound

### Issue requirements / progress
- [ ] Create the file at the right location.

### Directory Structure
Check the `example.txt` file under `/introduction/introduce_yourself/` and make a copy of that file under the same directory with `yourname.txt` as the title. Fill in your details. Commit it and send a PR.

#### Point of contact
Request for review from: Nisarg(@NJnisarg)

**Comment by SaurabhAgarwala** [comment]
I would like to work on this.

**Comment by adityagamer786** [comment]
I would like to work on this.

**Comment by mananpoddar** [comment]
@SaurabhAgarwala  I am assigning this issue to you. please make sure to make a pr in the given time limit.

**Comment by mnityesh28** [comment]
I would like to work on this.

**Comment by SaishMendke** [comment]
Please review my pull request and merge

**Comment by mnityesh28** [comment]
@NJnisarg Please review my code and merge it

**Comment by Kuljeet-123** [comment]
@NJnisarg please review my Pull Request #157

**Comment by Kuljeet-123** [comment]
@NJnisarg  please review my PR and merge into your repository and my PR id is #173

**Comment by GuptaNCode** [comment]
add my introduction

**Comment by NegaMage** [comment]
@NJnisarg requesting PR review, id #223 .

**Comment by SaurabhAgarwala** [comment]
**IMPORTANT**
Contributors, please note that the pull requests made for this issue will not be considered for Hacktoberfest 2019 as per [their guidelines on their core values](https://hacktoberfest.digitalocean.com/details). All the PRs made for this PR will be rendered invalid at a later stage. Please compensate for this PR by making another PR on a relevant issue.
