### ISSUE TITLE
File Transfer using UDP

### ISSUE THREAD

**Issue by arpi-r** [WebClub-NITK/Hacktoberfest-2k19#11]
### Description
Implement file transfer using UDP protocol and a client/server.

### Details
- Technical Specifications: Imlementation is expected in C language.
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Server code for file transfer
- [ ] Client code for file transfer
- [ ] Compiles and runs as expected
- [ ] A document explaining how to run the code.

### Resources
- [UDP](https://www.geeksforgeeks.org/user-datagram-protocol-udp/)
- [Socket Programming in C/C++](https://www.geeksforgeeks.org/socket-programming-cc/)
- [UDP Server-Client implementation in C](https://www.geeksforgeeks.org/udp-server-client-implementation-c/)

### Directory Structure
Create a folder named UDPFileTransfer in the systems directory and name the files as server.c and client.c in this folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @arpi-r
Feel free to ask any doubts and clarifications.

**Comment by Mksiyak** [comment]
i would like to work on it.
which type of file this will be ?
text,images or something else

**Comment by arpi-r** [comment]
The file will be a text file.
Go ahead and work on it!

**Comment by arpi-r** [comment]
@Mksiyak Could you please create a PR with your changes?

**Comment by abhinavjain20** [comment]
I would work on it

**Comment by arpi-r** [comment]
@abhinavjain20 sure, you can work on this!

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
