### ISSUE TITLE
Optimised Number of pairs

### ISSUE THREAD

**Issue by namanmanish** [WebClub-NITK/Hacktoberfest-2k19#12]
### Description
A sorted array will be given of n integers.A number will be given.You have to count the number of pairs in the array who sum up to the given number.

### Details
You don't have to read input or write output you just have to complete the given function.
This has to be solved in linear time( O(n) ).

**Comment by namanmanish** [comment]
Yes you can surely pick up this issue. Go ahead!

**Comment by lelloman** [comment]
Great thanks! So 2 questions, one is, does the solution have to be in C or could I do it Java? Second is, can the input array contain duplicates? For instance, if the input array is [1,1,1] and the sum 2, should the output be 1 (because one pair is 1,1) or 3 (because [x, x, _] [x, _, x] [_, x, x]?

**Comment by namanmanish** [comment]
For duplicates you can safely assume that the input will not contain any duplicates. It would be great if you do it in C. As you only have to complete the given function.

**Comment by namanmanish** [comment]
Seems good.Is working fine and running time is also linear.

**Comment by namanmanish** [comment]
Leave it the owner of this repository will see it and merge it as soon as possible. Thanks for contributing.

**Comment by predator4hack** [comment]
can i work on this problem?

**Comment by namanmanish** [comment]
Ya sure go for it.
