### ISSUE TITLE
Responsive Login Form

### ISSUE THREAD

**Issue by harshagrwl** [WebClub-NITK/Hacktoberfest-2k19#132]
### Description
Create a Login Page with Username and Password credentials and a submit button. The page should be responsive and validate the credentials if they are correct. In case of wrong credentials, the user should have a fixed number of login attempts.

### Details
- Technical Specifications: JavaScript, HTML, CSS
- Type of issue: Single
- Time Limit: 2 days

### Directory Structure
Create a folder named 'LoginPage' in the 'Development' directory and add your code there.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Request a review from @harshagrwl while submitting the pull request.

**Comment by adityagamer786** [comment]
I would like to work on this

**Comment by Kuljeet-123** [comment]
I would like to work on it

**Comment by Kuljeet-123** [comment]
@harshagrwl I have submitted my pull request .My pull request id is #155 ,Please review it and  merge it.

**Comment by harshagrwl** [comment]
@SaurabhAgarwala @harshnitk17  #155 is approved. Please merge it.
