### ISSUE TITLE
Get the difference between two text paragraphs(Ever used `git diff` !)

### ISSUE THREAD

**Issue by mananpoddar** [WebClub-NITK/Hacktoberfest-2k19#14]
### Description
Implement a feature similar to `git diff`. Write a function which takes two text paragraphs as argument and prints a paragraph highlighting the difference between these two paragraphs.

### Details
- Technical Specifications: You can use external libraries like google diff match patch.
- Type of issue: Single
- Time Limit: 1 Week.

### Issue requirements / progress
- [ ] apply required CSS to the diff paragraph, for example red marks for the words which are 
      missing and green for the words which are newly added.
- [ ] a GUI for showing the above is not necessary but remarkable.

### Resources
[google-diff](https://github.com/google/diff-match-patch)

### Directory Structure
Create a new folder called "diff" inside the development folder and add all the code corresponding to this issue inside /development/diff.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact me, @mananpoddar and also you can drop me a request for review! Happy learning!

**Comment by brendanAlbert** [comment]
If I can, I would like to try and tackle this one :)

**Comment by mananpoddar** [comment]
@brendanAlbert please go ahead.

**Comment by brendanAlbert** [comment]
Hi @mananpoddar, I finally implemented this features functionality!  Please let me know if you have any questions or comments.  Thank you! :)

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
