### ISSUE TITLE
Responsive Web Design

### ISSUE THREAD

**Issue by Sriram2001** [WebClub-NITK/Hacktoberfest-2k19#143]
### Description
Modify the static web page linked below to make it responsive. Currently, the web page is designed only for a desktop screen size. You are expected to design it for phone and tablet sizes and implement it by modifying the existing code.
You are allowed to resize and/or remove elements that may not be useful while the web page is being viewed on a phone or a tablet.
Link: [Web Page](https://github.com/Sriram2001/Basic-Web-Page)

### Details
- Technical Specifications: Preferably use only HTML and CSS with media queries to complete the task.
- Type of issue: [Single]
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Create the layout and design for mobile and tablet screen sizes.
- [ ] Implement it using HTML and CSS.

### Resources
- https://www.w3schools.com/html/
- https://www.w3schools.com/css/
- https://www.w3schools.com/cssref/css3_pr_mediaquery.asp

### Directory Structure
Create a directory named "ResponsiveWebPage" under the development folder and upload the completed design there. 

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
While submitting a PR request a review from Sriram Rao Udupi @Sriram2001

**Comment by Shuddhatm22** [comment]
I want to take up this issue

**Comment by abhinavpy** [comment]
You can take it up.

**Comment by nandakishore323** [comment]
still open?

**Comment by AnkitRai-22** [comment]
I want to take up the issue

**Comment by abhinavpy** [comment]
@nandakishore323 and @AnkitRai-22 both of you can start working on it. Whoever makes a pull request with the right code will have their code merged.

**Comment by AnkitRai-22** [comment]
I made a PR. @abhinavpy

**Comment by codebeast01** [comment]
I wanna take up the issue #143

**Comment by SaurabhAgarwala** [comment]
@AnkitRai-22 

> I made a PR. @abhinavpy

Please specify the PR number so that it's easy to review

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
