### ISSUE TITLE
Calculating Cache Line Size from a program

### ISSUE THREAD

**Issue by Shashwatha-Mitra** [WebClub-NITK/Hacktoberfest-2k19#15]
### Description
Write a C/C++ program to find the [Cache Line Size](https://encyclopedia2.thefreedictionary.com/cache+line) by using time measurements. The measurements are to be analyzed and plotted to identify the Line Size of the cache. 

### Details
- Technical Specifications: Implementation is expected in C/C++
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Measuring function execution times
- [ ] Providing the correct [access patterns](https://en.wikipedia.org/wiki/Memory_access_pattern).
- [ ] Plotting graph and analysis

### Resources
- Measuring time in C++: https://www.techiedelight.com/measure-elapsed-time-program-chrono-library/

### Directory Structure
Create a directory called 'Cache' under the systems folder. The folder must contain the program, an output file that contains the access pattern and execution times, and a graph for the same (as an image).

#### Note
Please claim the issue first by commenting here before starting to work on it.
While requesting a PR, request a review from @Shashwatha-Mitra
Doubts and clarifications are welcome

**Comment by rohit-mp** [comment]
Hey @Shashwatha-Mitra, any suggestions on which memory access pattern would be best to help me find the cache-line size?

**Comment by Shashwatha-Mitra** [comment]
Cache line brings in a line from memory based on locality of reference
So try using sequential memory access, and make appropriate time measurements

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
