### ISSUE TITLE
Single Byte XOR.

### ISSUE THREAD

**Issue by ryan-rozario** [WebClub-NITK/Hacktoberfest-2k19#150]
### Description
Write a function to encrypt some text using Single-byte XOR cipher.
Give the output as a hex-encoded string.

Write a function to break the single byte XOR cipher(input should be given as a hex encoded string). 
Try to decrypt the message using all keys from 0 to 255.
Evaluate each output using character frequency as the scoring measure. Choose the output with the highest score.
Return the key and the decrypted message.
To check your function obtain the plaintext and key for the following hex-encoded cipher text
`03246a2938333a3e252d382b3a2233666a3e222f6a25242f673e23272f6a3a2b2e6a62051e1a636a23396a2b246a2f242938333a3e2325246a3e2f292224233b3f2f6a3e222b3e6a292b2424253e6a282f6a29382b29212f2e666a283f3e6a382f3b3f23382f396a3e222f6a3f392f6a252c6a2b6a25242f673e23272f6a3a382f6739222b382f2e6a212f336a3e222f6a392b272f6a3923302f6a2b39666a25386a2625242d2f386a3e222b24666a3e222f6a272f39392b2d2f6a282f23242d6a392f243e646a03246a3e2223396a3e2f292224233b3f2f666a2b6a3a262b23243e2f323e6a23396a3a2b23382f2e6a3d233e226a2b6a382b242e25276a392f29382f3e6a212f336a622b2639256a382f2c2f38382f2e6a3e256a2b396a2b6a25242f673e23272f6a3a2b2e6364`

### Details
- Technical Specifications: Prefered Language is python
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Implement the encryption function for single-byte XOR.
- [ ] Implement a function to break single-byte XOR.

### Resources
https://www.codingunit.com/exclusive-or-xor-encryption

### Directory Structure
Create a folder in the `systems` directory corresponding to this issue number (150). Add the file `single_byte_xor.py` in `systems/150` folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @ryan-rozario

**Comment by entowan** [comment]
Hi, can I work on this issue?

**Comment by ryan-rozario** [comment]
@entowan Yes Sure.
