### ISSUE TITLE
Changing the base of a number

### ISSUE THREAD

**Issue by ryan-rozario** [WebClub-NITK/Hacktoberfest-2k19#151]
### Description
Write a python script to convert a number from one base to another. (maximum base 62)
The inputs to the program should be the number representation, the original base of the given number, the base to which the number has to be converted. 

Use the following symbol to value table
`

         '0': 0,
         '1': 1,
         '2': 2,
         '3': 3,
         '4': 4,
         '5': 5,
         '6': 6,
         '7': 7,
         '8': 8,
         '9': 9,
         'A': 10,
         'B': 11,
         'C': 12,
         'D': 13,
         'E': 14,
         'F': 15,
         'G': 16,
         'H': 17,
         'I': 18,
         'J': 19,
         'K': 20,
         'L': 21,
         'M': 22,
         'N': 23,
         'O': 24,
         'P': 25,
         'Q': 26,
         'R': 27,
         'S': 28,
         'T': 29,
         'U': 30,
         'V': 31,
         'W': 32,
         'X': 33,
         'Y': 34,
         'Z': 35,
         'a': 36,
         'b': 37,
         'c': 38,
         'd': 39,
         'e': 40,
         'f': 41,
         'g': 42,
         'h': 43,
         'i': 44,
         'j': 45,
         'k': 46,
         'l': 47,
         'm': 48,
         'n': 49,
         'o': 50,
         'p': 51,
         'q': 52,
         'r': 53,
         's': 54,
         't': 55,
         'u': 56,
         'v': 57,
         'w': 58,
         'x': 59,
         'y': 60,
         'z': 61,
`

### Details
- Technical Specifications: Prefered Language is python
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Implement the given task.

### Resources
https://math.wikia.org/wiki/Counting_in_different_bases

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @ryan-rozario

**Comment by abrahamfrancis** [comment]
@ryan-rozario I'll take this up.

**Comment by ryan-rozario** [comment]
OK sure. Yeah create directory 151 in algorithms folder
