### ISSUE TITLE
Random Number Generation

### ISSUE THREAD

**Issue by AnorexicAtticusFinch** [WebClub-NITK/Hacktoberfest-2k19#152]
### Description
Write the code to generate 1,00,000 random numbers and write them into a text file (Any language).

### Details
- Technical Specifications: Any language
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress

- [ ] - Implement the given task.

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @AnorexicAtticusFinch

**Comment by riaaniru2613** [comment]
@AnorexicAtticusFinch i want to work on this issue

**Comment by riaaniru2613** [comment]
@AnorexicAtticusFinch  please review the file and merge it

**Comment by predator4hack** [comment]
I want to work on it

**Comment by nandakishore323** [comment]
open or closed?

**Comment by Janmansh** [comment]
@AnorexicAtticusFinch  I would like to work on this.

**Comment by GuptaNCode** [comment]
i want to work on it

**Comment by Janmansh** [comment]
@AnorexicAtticusFinch Please review my PR. Thank you.
