### ISSUE TITLE
Converting small letters to capital letters

### ISSUE THREAD

**Issue by gnarayang** [WebClub-NITK/Hacktoberfest-2k19#16]
### Description
The objective of the program is to convert all the small letters in the sentence to capitals and ignore all other kinds of characters

### Details
- Technical Specifications:
- Type of issue: Single
- Time Limit: One day

### Issue requirements / progress
- [ ] Special characters are to be ignored.
- [ ] Letters which are already in Capital are to be ignored

### Resources
https://www.geeksforgeeks.org/conversion-whole-string-uppercase-lowercase-using-stl-c/

### Directory Structure
Create a folder named '16'(16 as in the issue number) in 'algorithms' folder. Name your program file as 'upper-case.cpp' or 'upper-case.c' accordingly. Add this program file to the folder '/algorithms/16'.

#### Point of contact
While submitting a PR, request a review from Narayan G (@gnarayang)

**Comment by shrinidhi99** [comment]
I am ready to resolve this issue.

**Comment by lryanle** [comment]
Since @shrinidhi99 hasn't resolved the issue, I'll take it on.

**Comment by adityagamer786** [comment]
I would like to work on this

**Comment by rahul0324** [comment]
I am solving this issue.

**Comment by Himanshu307** [comment]
I would like to work on it.

**Comment by Janmansh** [comment]
I would like to work on this issue.

**Comment by Janmansh** [comment]
@gnarayang  Please review my PR.

**Comment by dbarrerap** [comment]
I submitted my solution. Please review.

cc @gnarayang
