### ISSUE TITLE
Given an IPv4 Address, find its class.

### ISSUE THREAD

**Issue by krithikvaidya** [WebClub-NITK/Hacktoberfest-2k19#166]
### Description
Assuming classful addressing, given an IPv4 address, find its address class. If the entered IP address is invalid, your program should output an appropriate error message. Please follow the Input / Output format as shown below:

Example:
`Enter the IPv4 address: 194.200.20.55`
`This is a class C IPv4 address.`

### Details
- Technical Specifications: The task should be done in any of the below-mentioned programming languages. Please note that you should submit only a single file containing the code, and nothing else.
- Type of issue: Multiple
- Time Limit: 2 Days

### Issue requirements / progress
- [ ] Dart
- [ ] PHP
- [ ] Swift
- [ ] Kotlin
- [x] C
- [x] C++
- [x] C#
- [x] Java
- [x] Javascript
- [x] Python
- [x] Ruby
- [x] Golang

### Resources
[Classful Addressing](https://www.geeksforgeeks.org/introduction-of-classful-ip-addressing/)

### Directory Structure
Within this repository's 'systems' folder, create a folder called 'Issue 166 - IPv4 Class' (if it doesn't exist yet). Within this folder, place the file in which you have written the program for the task. The file name should be the name of the language you are using (e.g. - C.c, Python.py)

#### Note
Please claim the issue first by commenting here before starting to work on it. While claiming it, please mention the language that you will be using. Also, please check the checklist above and go through the comments to make sure that you aren't using the same language as someone else.
While submitting a PR, request a review from @krithikvaidya
Doubts and clarifications are welcome.

**Comment by aasthac67** [comment]
I would like to work on this.

**Comment by nirmalhk7** [comment]
I'd love to do this on C++.

**Comment by NJnisarg** [comment]
When you start working, if someone has already created the above mentioned folder(Issue 166 - IPv4 Class') Please simply put your file in that folder, do not again create a similar folder.

**Comment by krithikvaidya** [comment]
> I would like to work on this.

Sure, but edit your comment to mention the language you're using.

**Comment by krithikvaidya** [comment]
> I'd love to do this on C++.

Go ahead

**Comment by aasthac67** [comment]
> I would like to work on this.
> 
> Sure, but edit your comment to mention the language you're using.

Ill be working in C++

**Comment by krithikvaidya** [comment]
> > I would like to work on this.
> > Sure, but edit your comment to mention the language you're using.
> 
> Ill be working in C++

Sorry, since @nirmalhk7 mentioned that he'd be using C++ earlier, you'll need to use something else...

**Comment by aasthac67** [comment]
> I would like to work on this.
> Sure, but edit your comment to mention the language you're using.
> 
> Ill be working in C++
> 
> Sorry, since @nirmalhk7 mentioned that he'd be using C++ earlier, you'll need to use something else...

Ok ill go ahead with Python

**Comment by abrahamfrancis** [comment]
I'll do this in C.

**Comment by vishy-kothari-96** [comment]
Working in python for this issue

**Comment by descifrado** [comment]
I will do it in java

**Comment by lashewi** [comment]
I would like to work on this in C#

**Comment by bigblackclock** [comment]
i'll will do it in JS

**Comment by AdiY2j** [comment]
I will do it in GoLang

**Comment by AdiY2j** [comment]
Please review it @krithikvaidya

**Comment by XDBGAMES** [comment]
I will do it in Ruby

**Comment by XDBGAMES** [comment]
I will do it in Ruby

**Comment by SaurabhAgarwala** [comment]
@krithikvaidya Can this issue be closed now? Or are you expecting more PRs?

**Comment by krithikvaidya** [comment]
@SaurabhAgarwala Okay, close it now...
