### ISSUE TITLE
Implement QuickSort, MergeSort and RadixSort in C

### ISSUE THREAD

**Issue by mananpoddar** [WebClub-NITK/Hacktoberfest-2k19#18]
### Description
Implement sorting in c.

### Details
- Type of issue: Single
- Time Limit: 1 week.

### Issue requirements / progress
- [ ] comment your code properly.
- [ ] make as many functions as you can.

### Resources
[geeks-sorting](https://www.geeksforgeeks.org/sorting-algorithms/)

### Directory Structure
Create a new folder called "sort" inside the development folder and add all the code corresponding to this issue inside /algorithms/sort.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact me, @geekswaroop and also you can drop me a request for review! Happy learning!

**Comment by shrinidhi99** [comment]
I want to take up this issue and resolve it.

**Comment by akshettrj** [comment]
I would like to take up this problem.

**Comment by geekswaroop** [comment]
@akshettrj Sure! Although @shrinidhi99 has already referenced this issue, I would advise you to send a PR which contains the file written in C++

**Comment by shrinidhi99** [comment]
Yes. I have already got my c files merged so I had closed the issue. The issue was resolved

**Comment by abhinavjain20** [comment]
I would love to do this problem

**Comment by ArquiteturaJoel** [comment]
I would like to take up this problem.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
