### ISSUE TITLE
Build a 2-input 2-output Deep Learning model.

### ISSUE THREAD

**Issue by mananpoddar** [WebClub-NITK/Hacktoberfest-2k19#19]
### Description
Complete a Jupyter notebook which uses Keras Functional API and implement the model (Use your favourite dataset)

### Details
- Type of issue: Single
- Time Limit: 1 week.

### Issue requirements / progress
- [ ] mention the link to the dataset that you have used.

### Directory Structure
Create a new folder called "SimpleNeuralNet" inside the development folder and add all the code corresponding to this issue inside /machineLearning/SimpleNeuralNet.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact me, @geekswaroop and also you can drop me a request for review! Happy learning!

**Comment by kampaitees** [comment]
I'm ready to solve it

**Comment by mananpoddar** [comment]
@kampaitees  go ahead.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
