### ISSUE TITLE
Encode and Decode using Caesar script (CRYPTOGRAPHY) 

### ISSUE THREAD

**Issue by adityachirania** [WebClub-NITK/Hacktoberfest-2k19#192]
### Description
Write a C/C++/Python program that takes in a message (A STRING) and encrypts the message using Caesar script: 
-[ ]Define an encryption function that takes the message and a key as a parameter and encrypts the message.
-[ ]Define a decryption function that takes the encrypted message and key as parameter and returns the decrypted message.
-[ ] Also write a function to brute forces all possible keys into the encrypted message.

### Details
- Technical Specifications:  C/C++ /Python
- Type of issue: [Single] 
- Time Limit: 2 days

### Resources
http://practicalcryptography.com/ciphers/caesar-cipher/

### Directory Structure
Create a folder "Caesar_script" in the algorithms folder and add your code to that file. 

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Please contact @adityachirania for any queries. Happy learning!

**Comment by nirmalhk7** [comment]
@adityachirania I'd love to do this on C++.

**Comment by csp98** [comment]
I would like to do this in Python.

**Comment by adityachirania** [comment]
@nirmalhk7 you may take it up.

**Comment by adityachirania** [comment]
@csp98 im sorry some else requested before you

**Comment by adityachirania** [comment]
@csp98 you can take it up as well!

**Comment by nirmalhk7** [comment]
My code is ready, but I'm waiting for [this PR](https://github.com/WebClub-NITK/Hacktoberfest-2k19/pull/203) to be merged.

**Comment by adityachirania** [comment]
@nirmalhk7 The code has a few bugs
try encrypting "zack and cody" with key 1 and your encrypted string is giving me "{bdl boe dpez"
but "{" is not a part of the casesar scrpt! secondly even if try to decrypt this "{bdl boe dpez" back with key 1 it doesnt give me back "zack and cody". Please resolve the bugs in your program!

**Comment by abhinavjain20** [comment]
I would like to do it with C++

**Comment by adityachirania** [comment]
Yes you may take it up

**Comment by bpbrum** [comment]
Hey! I would like to do this in Python.

**Comment by ArquiteturaJoel** [comment]
I would like to take up this problem Python or if possible java too.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
