### ISSUE TITLE
Vigenére cipher

### ISSUE THREAD

**Issue by Mohit-Mithra** [WebClub-NITK/Hacktoberfest-2k19#193]
### Description
Given a key, write a program to encrypt/decrypt the given text using Vigenére cipher.

### Details
- Technical Specifications: Langauge of your choice(C, C++, python, Java, Go, Ruby)
The task should be done in any of the above-mentioned programming languages. Please note that you should submit only a single file containing the code, and nothing else.
- Type of issue: Multiple
- Time Limit: 2 days

### Resources
https://en.m.wikipedia.org/wiki/Vigenère_cipher
http://practicalcryptography.com/ciphers/classical-era/vigenere-gronsfeld-and-autokey/

### Directory Structure
Create a folder named '193'(193 as in the issue number) in 'systems' folder. Name your program file as 'vigenere.cpp' or 'vigenere.c' or 'vigenere.py', etc as seen appropriate to the language of your choice. Add this program file to the folder '/systems/193'.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
While submitting a PR, request a review from @Z0marlin 
Doubts and clarifications are welcome.

**Comment by him1anshu** [comment]
I want to work on this issue.@Mohit-Mithra

**Comment by him1anshu** [comment]
the input will be in uppercase and without spaces by default or it can also take input in lowercase and with spaces then it should do the conversion after changing the input into uppercase and without spaces?@Mohit-Mithra @Z0Marlin

**Comment by Z0Marlin** [comment]
@him1anshu Go ahead!

**Comment by him1anshu** [comment]
ok...thanks.@Z0Marlin

**Comment by him1anshu** [comment]
Please review the code.I have made the changes.@Z0Marlin
