### ISSUE TITLE
BFS Traversal

### ISSUE THREAD

**Issue by ArqumShaikh** [WebClub-NITK/Hacktoberfest-2k19#20]
### Description
Write an efficient code to print the Breadth First Search traversal of a graph in C++.

### Details
- Type of issue: Single
- Time Limit: 2 Days
### Issue requirements / progress
- [ ] Implement algorithm to print the bfs traversal of graph

### Resources
[BFS Tutorial](https://www.hackerearth.com/practice/algorithms/graphs/breadth-first-search/tutorial/)

### Directory Structure
Create a new folder called "bfs" inside algorithms folder and add all code related to this issue in the development/bfs folder

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact me,@ArqumShaikh and also you can drop me a request for review! Happy learning!

**Comment by waterfl0w** [comment]
I would like to claim this issue.

**Comment by ArqumShaikh** [comment]
> I would like to claim this issue. Is it sufficient if the implementation is in Java, or do you prefer another programming language e.g. Python?

@waterfl0w The implementation should be in C++

**Comment by waterfl0w** [comment]
Sure, I can do that.

**Comment by ArqumShaikh** [comment]
> Sure, I can do that.

Fine, I am assigning this issue to you.

**Comment by vishy-kothari-96** [comment]
@ArqumShaikh Since no one has made a PR for this issue, can i work on this?

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by vishy-kothari-96** [comment]
@ArqumShaikh Okay I'm working on it!

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
