### ISSUE TITLE
Salt and pepper noise remover using OpenCV

### ISSUE THREAD

**Issue by apoorva-mk** [WebClub-NITK/Hacktoberfest-2k19#204]
### Description
Write a script to remove salt and pepper noise from an image using Python using OpenCV library ( Preferably avoid library functions except for reading and writing images )

### Details
- Type of issue: [Single]
- Time Limit: 2 days

### Issue requirements / progress
- [x] Implemented in python
- [x] Use OpenCV

### Resources
https://opencv.org/

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
In the PR sent, comment @apoorva-mk.

**Comment by kampaitees** [comment]
I'm solving it

**Comment by apoorva-mk** [comment]
@kampaitees please submit your PR within two days of claiming it :D

**Comment by kampaitees** [comment]
Created the pull request, plz merge it.

**Comment by compiletimeterror** [comment]
ready to solve it

**Comment by apoorva-mk** [comment]
> ready to solve it

This issue had already been claimed and PR had been sent so your PR will not be merged, unfortunately.
