### ISSUE TITLE
Extracting colors from an image

### ISSUE THREAD

**Issue by SakshatRao** [WebClub-NITK/Hacktoberfest-2k19#206]
### Description
Extract all primary and secondary colors (i.e. red, green, blue, yellow, magenta and cyan) from the given image. You need to get six images corresponding to the six colors extracted. The color extraction part has to be done manually and not through modules like OpenCV. You need to work on the below image.

![color_image](https://user-images.githubusercontent.com/39237794/66200304-5d008280-e6be-11e9-9ae5-22ac1b1c2d69.png)

### Details
- Technical Specifications: Python is preferred
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Python
- [ ] OpenCV, Pillow or any other image processing module (only for loading the image)

### Resources
https://www.geeksforgeeks.org/working-images-python/

### Directory Structure
Create a folder called '206' in the 'machineLearning' directory. Add the required python script or jupyter notebook in machineLearning/206.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
While submitting Pull Requests, request from @ameyanrd or @SakshatRao

**Comment by HassanAlsamahi** [comment]
Hello, I'd like to work on this issue

**Comment by SakshatRao** [comment]
Hello there! You can go ahead and work on this issue. However, please submit the PR within two days...

**Comment by HassanAlsamahi** [comment]
> Hello there! You can go ahead and work on this issue. However, please submit the PR within two days...

okay thanks

**Comment by SakshatRao** [comment]
Since the two day deadline was not met, this issue is open again.

**Comment by HassanAlsamahi** [comment]
> Since the two day deadline was not met, this issue is open again.

@SakshatRao  I sent a pull request yesterday (7 oct)

**Comment by SakshatRao** [comment]
@HassanAlsamahi I'm sorry about not realizing you had sent a pull request. Also, the pull request was supposed to properly reference this issue. Anyways, that's not a problem. The code works great. Thank you for your participation. I'll request your PR to be merged. This issue is closed.
