### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by ansen16** [WebClub-NITK/Hacktoberfest-2k19#207]
### Description
Write an efficient code to find and print the path between 2 nodes in a graph using Dijkstra's Algorithm. The Implementation should be in C++.

### Details
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Implement Dijkstra's Algorithm

### Resources
https://www.hackerearth.com/practice/notes/dijkstras-algorithm/

### Directory Structure
Create a new folder called "Dijkstras" inside algorithms folder and add all code related to this issue in the algorithms/Dijkstras folder

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact @ansen16 or  @ArqumShaikh and also you can drop us a request for review! Happy learning!

**Comment by aasthac67** [comment]
I like to work on this issue

**Comment by ansen16** [comment]
> I like to work on this issue

Sure, I'm assigning it to you.

**Comment by aasthac67** [comment]
Can you please review the code

**Comment by ansen16** [comment]
> @ansen16 Can you please review the code

Could you run it for a sample input and show the output?

**Comment by aasthac67** [comment]
> @ansen16 Can you please review the code
> 
> @aasthac67  Could you run it for a sample input and show the output?

@ansen16 The attached file has a Dijkstras.png which contains the screenshot of the input and the output.

**Comment by aasthac67** [comment]
![Dijkstras](https://user-images.githubusercontent.com/38806427/66493063-13e56f80-eabe-11e9-8099-45a7ac74db9f.png)

**Comment by aasthac67** [comment]
![Dijkstras](https://user-images.githubusercontent.com/38806427/66493383-a259f100-eabe-11e9-9f64-53895d162a4e.png)

@ansen16 This is the sample input and output.

**Comment by ansen16** [comment]
> > @ansen16 Can you please review the code
> > @aasthac67  Could you run it for a sample input and show the output?
> 
> @ansen16 The attached file has a Dijkstras.png which contains the screenshot of the input and the output.

The output of the 2nd and 3rd sample inputs are wrong. From 0 to 5, the optimal path is 0->7->6->5. (total weight 11). The path in the answer has a total weight of 16.
Similarly from 0 to 6, 0->7->6 is the best. (total weight 9). While the path in the answer has a total weight of  18.
Your code outputs a longer path (in both cases) with is incorrect according to Dijkstra's algorithm.
Please check this and make corrections in your code wherever necessary.

**Comment by abhinavjain20** [comment]
I would like to work on this issue.

**Comment by ansen16** [comment]
> I would like to work on this issue.

sure go ahead

**Comment by gaurivn** [comment]
I would like to work on this issue.
