### ISSUE TITLE
Data visualization using Searborn/Bokeh Library

### ISSUE THREAD

**Issue by mananpoddar** [WebClub-NITK/Hacktoberfest-2k19#21]
### Description
visualization of data before applying machine learning models is a very important step in getting amazing results! Please use seaborn/bokeh libraries to visualize the data.
Take your favourite dataset and visualize the data in a python notebook. 
### Details
- Type of issue: Single
- Time Limit: 1 week.

### Issue requirements / progress
- [ ] Atleast 5 charts

### Directory Structure
Create a new folder called "visualisation" inside the development folder and add all the code corresponding to this issue inside /machineLearning/visualisation.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact me, @geekswaroop and also you can drop me a request for review! Happy learning!

**Comment by kampaitees** [comment]
I'm going to do it

**Comment by mananpoddar** [comment]
@kampaitees  please work on it.

**Comment by kampaitees** [comment]
@mananpoddar It is already merged to the repo but it is not showing here why?

**Comment by kampaitees** [comment]
@mananpoddar Here is link for  merged folder 
https://github.com/WebClub-NITK/Hacktoberfest-2k19/tree/master/machineLearning/Visualisation

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
