### ISSUE TITLE
String Tokenization in C

### ISSUE THREAD

**Issue by suhasks123** [WebClub-NITK/Hacktoberfest-2k19#22]
### Description
Write a C program to tokenize an input string based on given delimiters. For example, if the input string is "I love Open Source" and the delimiter is " ", your code should create a string array of the form {"I","love","Open","Source"}. The string and the delimiter are the inputs.

### Details
- Technical Specifications: The language to be used is C
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Should compile without any errors.
- [ ] Should run as expected.

### Resources
- [https://www.geeksforgeeks.org/commonly-used-string-functions-in-c-c-with-examples/](https://www.geeksforgeeks.org/commonly-used-string-functions-in-c-c-with-examples/)
- [https://en.wikibooks.org/wiki/C_Programming/String_manipulation](https://en.wikibooks.org/wiki/C_Programming/String_manipulation)

### Directory Structure
Create a directory called 'StringTokenization' in the systems directory and upload your program there.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While requesting a PR, request a review from @suhasks123.
Doubts and clarifications are welcome.

**Comment by A1phyte** [comment]
Can I take this issue?

**Comment by suhasks123** [comment]
> Can I take this issue?

Yeah go ahead

**Comment by nandakishore323** [comment]
Can I Take this please,? please

**Comment by suhasks123** [comment]
> Can I Take this please,? please

Cool, go ahead.

**Comment by nandakishore323** [comment]
#22 StringTokenization. Wrote the code. 
@suhasks123 can you please review and suggest changes

**Comment by nandakishore323** [comment]
systems/StringTokenization/main.c

**Comment by nandakishore323** [comment]
Please Review My code and merge if its okay 
#197

**Comment by suhasks123** [comment]
I have reviewed PR #197 that solves issue #22. Please merge it @SaurabhAgarwala
