### ISSUE TITLE
XOR Linked List Implementation

### ISSUE THREAD

**Issue by SaurabhAgarwala** [WebClub-NITK/Hacktoberfest-2k19#228]
### Description
Implement XOR linked list.

### Details
- Technical Specifications: Can use any of C/C++/Python/Java (PRs for different languages will be accepted. Claim the issue specifying the language with which you will work)
- Type of issue: Single
- Time Limit: ~24 hours after claiming the issue

### Issue requirements / progress
- [ ] Implement XOR Linked list which can be traversed both forward and backward.
- [ ]  Create a README to explain the work done.

### Resources
- [XOR Linked List Tutorial](https://www.geeksforgeeks.org/xor-linked-list-a-memory-efficient-doubly-linked-list-set-1/)

### Directory Structure
Create a folder named as the language of the code with which you are implementing the issue and place it under another folder named `xor_linked_list` under the `algorithms` folder of the main repo. Add the relevant files under the language folder created. For e.g., for python the relevant files have to be placed under `algorithms/xor_linked_list/python`

#### Note
Please claim the issue first by commenting here before starting to work on it.

When you have added the relevant files and made the PR, please request a review from @SaurabhAgarwala or @viveshCodes

**Comment by adityakaria** [comment]
I'd like to work on this in C++ please. Thanks!

**Comment by SaurabhAgarwala** [comment]
Sure, go ahead. Please send your PR by 11:59 pm IST

**Comment by gaurivn** [comment]
I would like to work on this issue in C.

**Comment by SaurabhAgarwala** [comment]
@gaurivn Sure go ahead

**Comment by gaurivn** [comment]
@SaurabhAgarwala I submitted my pull request yesterday within the time limit allotted to me, kindly review it.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
