### ISSUE TITLE
Social OAuth

### ISSUE THREAD

**Issue by SaurabhAgarwala** [WebClub-NITK/Hacktoberfest-2k19#229]
### Description
Create a simple Social OAuth Login page and give an option of sign out such that signing out clears the cookies of browser.

### Details
- Technical Specifications: Can use any available Libraries/Frameworks for the task
- Type of issue: Single
- Time Limit: ~48 hours after claiming the issue

### Issue requirements / progress
- [ ] Create a Social OAuth Login Page. Give a button to sign out which will log out the user and clear the cookies of the browser.
- [ ] Create a README to explain the work done.

### Resources
- [OAuth](https://fosstack.com/how-to-add-google-authentication-in-django/)
- [Clear Cookies](https://stackoverflow.com/questions/14401398/how-to-clear-cookies-using-django/32375882#32375882)

### Directory Structure
Create a folder named `OAuth_Cookies` under the `development` folder of the main repo. Add the relevant files under this folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.
When you have added the relevant files and made the PR, please request a review from @SaurabhAgarwala @viveshCodes

**Comment by KshitijMhatre** [comment]
I'd like to work on this. Thanks!

**Comment by viveshCodes** [comment]
@KshitijMhatre Sure , go ahead. Please send a PR when relevant files a added.

**Comment by KshitijMhatre** [comment]
@viveshCodes The first reference link seems to be broken. Is it okay if I implement this using node-express ?

**Comment by viveshCodes** [comment]
@KshitijMhatre Absolutely okay. Go ahead with node-express.

**Comment by KshitijMhatre** [comment]
@viveshCodes implemented OAuth using `gapi`. Wanted to do it using `passport.js` but didn't get time. Hope this one is helpful.

**Comment by viveshCodes** [comment]
@KshitijMhatre It works well .
 @SaurabhAgarwala  @NJnisarg It seems good to me . PR can be merged.
