### ISSUE TITLE
SQL Operations using MySQL or SQLite3

### ISSUE THREAD

**Issue by krithikvaidya** [WebClub-NITK/Hacktoberfest-2k19#23]
### Description
Using MySQL or SQLite3, create a database named 'smartphones'.
Within this database, create a single table 'smartphone_details'. In this table, create the
following fields with the appropriate types and constraints:

- smartphone_id: the primary key
- model_name: the name of the smartphone's model. max length of 50 characters
- company_name: the company that created the smartphone. max length of 30 characters
- price: the price of the smartphone, in the format <rupees>.<paise> (eg: 10999.00)
- os: the base operating system of the phone. (eg: Android, iOS)
- release_date: the release date of the smartphone.

Then, insert the following tuples of data into the 'smartphone_details' table:

(1, 'Pixel 3', 'Google', 57000.00, 'Android', '2018-10-09'),
(2, 'iPhone XR', 'Apple', 49999.00, 'iOS', '2018-09-12'),
(3, 'iPhone 11 Pro', 'Apple', 99900.00, 'iOS', '2019-09-10'),
(4, 'Galaxy Note 10 Plus', 'Samsung', 85000.00, 'Android', '2019-08-07'),
(5, 'iPhone XS Max', 'Apple', 94999.00, 'iOS', '2018-09-12'),
(6, 'Galaxy A50s ', 'Samsung', 19949.00, 'Android', '2019-08-22'),
(7, 'Galaxy S9', 'Samsung', 44990.00, 'Android', '2018-03-16'),
(8, 'ROG Phone II', 'Asus', 37999.00, 'Android', '2019-09-23'),
(9, 'Mi A3', 'Xiaomi', 12999.00, 'Android', '2019-08-21'),
(10, 'Galaxy A10', 'Samsung', 7990.00, 'Android', '2019-03-02')

Now, perform the following queries on your database (Print values in all columns for each tuple):

1. Display all smartphones with price less than Rs. 60,000
2. List all smartphones released between 1st March, 2018 to 31st December, 2018.
3. Find the 2 cheapest smartphones released by Samsung after January 1, 2019 (less expensive one should be displayed first).

### Details
- Technical Specifications: The task should be done either in MySQL or SQLite. You can submit either a .sql script or a .txt file containing the commands to perform the task
- Type of issue: Multiple
- Time Limit: 1 Day

### Issue requirements / progress
- [x] MySQL
- [x] SQLite3

### Resources
[MySQL Youtube Tutorial](https://www.youtube.com/watch?v=yPu6qV5byu4)
[SQLite3 Youtube Tutorial](https://www.youtube.com/watch?v=QjICgmk31js)

### Directory Structure
Within this repository's 'systems' folder, create a folder called 'SQL Operations' (if it doesn't exist yet). Within this folder, place the file in which you have written the script for the task. The file name should be either MySQL(.txt/.sql) or SQLite3 (.txt/.sql)

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @krithikvaidya
Doubts and clarifications are welcome.

**Comment by nirmalhk7** [comment]
I'll try this.

**Comment by satooru** [comment]
I'd like to try this one too!

**Comment by krithikvaidya** [comment]
> I'll try this.
Cool! Just mention whether you'll be doing it in MySQL or SQLite3

**Comment by krithikvaidya** [comment]
> I'll try this.

Cool! Just mention whether you're doing it in MySQL or SQLite3

**Comment by krithikvaidya** [comment]
> I'd like to try this one too!

Sure, but you'll need to select the DBMS that @nirmalhk7 isn't using

**Comment by satooru** [comment]
Ok, I guess...

I hope SQLite isn't too different from MySQL.

**Comment by satooru** [comment]
@nirmalhk7 for now, I'll be using SQLite. Let me know if you want switch.

**Comment by nirmalhk7** [comment]
I'll be using MySQL.

**Comment by benlop27** [comment]
I'll Take It! Using MySQL

**Comment by krithikvaidya** [comment]
> I'll Take It! Using MySQL

Hey sorry, both the issues have already been taken...

**Comment by adityagamer786** [comment]
I would like to work on this

**Comment by krithikvaidya** [comment]
> I would like to work on this

Sorry, both issues have been taken.

**Comment by NJnisarg** [comment]
Why was this issue closed? Is some PR merged?
