### ISSUE TITLE
Housing Prices Prediction using Regression

### ISSUE THREAD

**Issue by SkaMessi10** [WebClub-NITK/Hacktoberfest-2k19#234]
### Description
This task is based on predicting the value of houses using the dataset given below. The information about each column of the dataset is also attached. Your task is to build regression model(linear or polynomial regression based on your discretion), to accurately predict the housing prices.
[housingdata.docx](https://github.com/WebClub-NITK/Hacktoberfest-2k19/files/3692859/housingdata.docx)
[housingInfo.docx](https://github.com/WebClub-NITK/Hacktoberfest-2k19/files/3692860/housingInfo.docx)

### Details
- Technical Specifications: Python should be used and use only regression models.
- Type of issue: Single
- Time Limit: 1 day.

### Issue requirements / progress
- [ ] Try not to overfit the data.
- [ ] Use python code, preferably in Jupyter notebook.

### Resources
-https://towardsdatascience.com/linear-regression-on-boston-housing-dataset-f409b7e4a155

### Directory Structure
Create a directory called 'Housing_Prices' in the 'machinelearning' directory and upload your python code or notebook there.
#### Note
Please claim the issue first by commenting here before starting to work on it.
While requesting a PR, request a review from @SkaMessi10.
Any doubts or clarifications will be cleared promptly.

**Comment by Shuddhatm22** [comment]
I want to take this issue

**Comment by SkaMessi10** [comment]
> I want to take this issue

Go ahead and start working on it. I'm assigning this issue to you.
