### ISSUE TITLE
Build a KNN Classifier from scratch

### ISSUE THREAD

**Issue by shruthanr** [WebClub-NITK/Hacktoberfest-2k19#236]
### Description
You are given some starter code. You are required to build on it in order to build a K-Nearest Neighbors classifier using only NumPy (and possibly other libraries for individual sub parts like calculating mode of a list, sorting a list etc). However you cannot use a ready made classifier of any sort from any library. 

### Details
- Type of issue: Multiple 
- Time Limit: 3 days
### Issue requirements / progress
- [ ] Complete the given code to get a running classifier
- [ ] You can additionally use techniques to do each sub part/function optimally. 

### Resources
https://docs.scipy.org/doc/
https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm

### Directory Structure
The starter code to be modified is given in the KNN directory under machineLearning.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @shruthanr

**Comment by shashikanthgk** [comment]
I am taking up this issue

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
