### ISSUE TITLE
TRIE datastructure Implementation

### ISSUE THREAD

**Issue by KshitijMhatre** [WebClub-NITK/Hacktoberfest-2k19#238]
### Description
Implement TRIE data-structure.

### Details
- Technical Specifications: Can use any of C/C++/Python/Java (PRs for different languages will be accepted. Claim the issue specifying the language with which you will work)
- Type of issue: Single
- Time Limit: ~24 hours after claiming the issue

### Issue requirements / progress
- [ ] Implement the TRIE data-structure in chosen language.
- [ ]  Create a README to explain the work done.

### Resources
[wikipedia](https://en.wikipedia.org/wiki/Trie)
[tutorial](https://www.geeksforgeeks.org/trie-insert-and-search/)

### Directory Structure
Create a folder named as the language of the code with which you are implementing the issue and place it under another folder named `TRIE` under the `datastructure` folder of the main repo. Add the relevant files under the language folder created. For e.g., for python the relevant files have to be placed under `datastructure/TRIE/python`

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
When you have added the relevant files and made the PR, please request a review from @KshitijMhatre

**Comment by KshitijMhatre** [comment]
I'd like to work on this in C .

**Comment by KshitijMhatre** [comment]
@SaurabhAgarwala ,@krithikvaidya please review the issue and provided PR for the same. Should I add any of the maintainers to the issue description ?

**Comment by SaurabhAgarwala** [comment]
@KshitijMhatre We won't be entertaining cases where the issue and the PR both are by the same person. Request you to close both issue and the PR or just this PR and mentor the issue created by you. You are free to make PRs for any of the issues not created by you.

**Comment by KshitijMhatre** [comment]
@SaurabhAgarwala sure no problem. Closing the PR.

**Comment by ArquiteturaJoel** [comment]
I would like to take up this problem

**Comment by KshitijMhatre** [comment]
@ArquiteturaJoel sure go ahead.
