### ISSUE TITLE
GCD of 2 Numbers

### ISSUE THREAD

**Issue by AnorexicAtticusFinch** [WebClub-NITK/Hacktoberfest-2k19#239]
### Description
Find the GCD of any two given numbers (Take input from the user) efficiently.

### Details
- Technical Specifications: Any language
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] - Implement the given task.

### Resources
https://en.wikipedia.org/wiki/Euclidean_algorithm

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @AnorexicAtticusFinch

**Comment by nandakishore323** [comment]
Can i work on this please?

**Comment by NegaMage** [comment]
I'd like to work on this too.

**Comment by akshettrj** [comment]
I want to work on this problem

**Comment by Kuljeet-123** [comment]
I would like to work on it.

**Comment by jaywantpatel** [comment]
I would like to work on this
