### ISSUE TITLE
 Improvising C  program of swapping with maximum element in array 

### ISSUE THREAD

**Issue by adityachirania** [WebClub-NITK/Hacktoberfest-2k19#24]
### Description
This folder contains a C program. The C program has a maximum() function and swap() function. Please fix the bugs in the function and add the following features:
-[ ]Run the Program as many times as the user wants.
-[ ]We want to work with larger input elements in array 
-[ ]Our swap function uses a temp variable please try swapping without the temp variable 

### Details
- Technical Specifications:Language to be used is C
- Type of issue: Single  
- Time Limit: 2 days

### Resources
https://www.learn-c.org/

### Directory Structure
Create a new folder called "Swap_with_max" inside algorithms folder and add all code related to this issue in the algorithms/Swap_with_max folder

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact me,@adityachirania and also you can drop me a request for review! Happy learning!

**Comment by rak108** [comment]
can i work on this program?

**Comment by adityagamer786** [comment]
I would like to work on this

**Comment by adityagamer786** [comment]
I would like to work on this

**Comment by adityachirania** [comment]
Yes you can go ahead

**Comment by adityachirania** [comment]
Sorry someone else already asked for it first

**Comment by rak108** [comment]
given a PR, kindly check
https://github.com/WebClub-NITK/Hacktoberfest-2k19/pull/179

**Comment by adityachirania** [comment]
@rak108 The code Looks great!
 @harshnitk17 Please merge the PR. 
Closing the issue!

**Comment by Janmansh** [comment]
I would like to work on this.

**Comment by deeptadevkota** [comment]
Can I work on this?

**Comment by rak108** [comment]
@adityachirania thanks!

**Comment by Himanshu307** [comment]
I would like to work on this.

**Comment by Himanshu307** [comment]
Given a PR, kindly check #242

**Comment by Janmansh** [comment]
@adityachirania  Please review my PR.

**Comment by pratyanshupandey** [comment]
May I start working on this issue?

**Comment by adityachirania** [comment]
@Himanshu307 @deeptadevkota @Janmansh 
Im sorrry but rakshitha 's PR had already been accepted ! Im just waiting for  @harshnitk17  to merge the PR
