### ISSUE TITLE
BST Implementation

### ISSUE THREAD

**Issue by AnorexicAtticusFinch** [WebClub-NITK/Hacktoberfest-2k19#240]
### Description
Implement BST data structure with insert, delete, find and inorder printing functions.

### Details
- Technical Specifications: Any language
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] - Implement the find function
- [ ] - Implement the insert function
- [ ] - Implement the delete function
- [ ] - Implement the inorder traversal function

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @AnorexicAtticusFinch

**Comment by Mksiyak** [comment]
i would like to work on it.

**Comment by gaurivn** [comment]
I would want to work on this issue
