### ISSUE TITLE
Fix the bugs in the given implementation of Socket based Inter Process Communication

### ISSUE THREAD

**Issue by suhasks123** [WebClub-NITK/Hacktoberfest-2k19#25]
### Description
Given is a program which implements Inter Process Communication using Sockets. Find the bugs in the program. The expected output is:
`-->What is Hacktoberfest?`
`-->It is a celebration of Open Source:)`

### Details
- Technical Specifications: The program is written in C
- Type of issue: Single
- Time Limit: 1 day
- Code:
[IPC-using-Sockets.zip](https://github.com/WebClub-NITK/Hacktoberfest-2k19/files/3675899/IPC-using-Sockets.zip)

### Issue requirements / progress
- [ ] Should display the expected output.

### Resources
- [https://opensource.com/article/19/4/interprocess-communication-linux-networking](https://opensource.com/article/19/4/interprocess-communication-linux-networking)
- [https://www.gnu.org/software/libc/manual/html_node/Socket-Pairs.html](https://www.gnu.org/software/libc/manual/html_node/Socket-Pairs.html)

### Directory Structure
Create a directory with the name 'IPC-Socket-bugfix' in the systems directory and upload the corrected code in that directory.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While requesting a PR, request a review from @NJnisarg.
Doubts and clarifications are welcome.

**Comment by NJnisarg** [comment]
There is a file in /systems/IPC-using-Sockets.c
Use that file and fix bugs in that. Submit your patch by making changes to the file itself. Add @NJnisarg as a request for review.
If any doubts, ask on this thread.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
