### ISSUE TITLE
Convert Python code to C/C++ code

### ISSUE THREAD

**Issue by aksh555** [WebClub-NITK/Hacktoberfest-2k19#260]
### Description
You are given the code for a task in Python. Your goal is to convert this to C/C++, which performs the same task.

### Details
- Technical Specifications:
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Implement the given task

### Resources
https://www.geeksforgeeks.org/stdstring-class-in-c/

### Directory Structure
Create a folder called 'python-to-cpp' in the 'algorithms' directory. Add the required program in algorithms\python-to-cpp.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @aksh555

**Comment by him1anshu** [comment]
You will give a specific task or code in python to convert it into c/c++ program?@aksh555

**Comment by aksh555** [comment]
Yes, it will be added soon.

**Comment by him1anshu** [comment]
Then I will like to work on this issue. Please assign it to me.  @aksh555

**Comment by divas18** [comment]
I will upload it as soon as possible

**Comment by SaurabhAgarwala** [comment]
@him1anshu Relevant files have been added. You can start working on it

**Comment by him1anshu** [comment]
Ok.Thanks@SaurabhAgarwala

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
