### ISSUE TITLE
Searching for Cycles in a Directed Graph

### ISSUE THREAD

**Issue by AnorexicAtticusFinch** [WebClub-NITK/Hacktoberfest-2k19#271]
### Description
Write a program that makes a directed graph using user input and prints True if a cycle exists and False otherwise.

### Details
- Technical Specifications: C/C++
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Taking input and making the Graph
- [ ] Searching for a Cycle

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @AnorexicAtticusFinch

**Comment by gaurivn** [comment]
I would like to take up this issue and work on it.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
