### ISSUE TITLE
Implement Tries

### ISSUE THREAD

**Issue by AnorexicAtticusFinch** [WebClub-NITK/Hacktoberfest-2k19#272]
### Description
Implement the Tries Data Structure: Insert, Delete and Search.

### Details
- Technical Specifications: C/C++
- Type of issue: Single
- Time Limit: 2 Days

### Issue requirements / progress
- [ ] Search
- [ ] Insert
- [ ] Delete

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, please request a review from @AnorexicAtticusFinch

**Comment by NegaMage** [comment]
I'd like to take this up in C++. Also how would the delete function work, would it be only for leaf nodes?

**Comment by NegaMage** [comment]
Implemented in c++ with example code, in PR #279 
Requesting review, @AnorexicAtticusFinch

**Comment by AnorexicAtticusFinch** [comment]
@SaurabhAgarwala This can be merged.
