### ISSUE TITLE
Add heapsort implementation

### ISSUE THREAD

**Issue by harshsri2208** [WebClub-NITK/Hacktoberfest-2k19#275]
In the directory algorithms/sort there are other sorting algorithms but we do not have implementation of heap sort.

**Comment by nandakishore323** [comment]
I want to take this issue

**Comment by harshsri2208** [comment]
I have already created a pull request for this issue

**Comment by gaurivn** [comment]
I would like to work on this in Java.

**Comment by harshsri2208** [comment]
@gaurivn all the programs in the directory are in C. I'm not sure if you can write programs in Java.

**Comment by harshsri2208** [comment]
my pull request was merged. I am closing this issue
