### ISSUE TITLE
Improve Survey web app

### ISSUE THREAD

**Issue by namanmanish** [WebClub-NITK/Hacktoberfest-2k19#276]
### Description
Task 1:
This web application conducts a survey.The survey has few basic questions like state,city etc.
This is developed in django. Here for the questions I have created a dropdown. This dropdown is hardcoded that is in the models.py file the key and the attribute is matched instead of reading from the database.You have to change it in such a way that you can directly read from the database instead of hardcoding it.  
Task 2:
There is statistics page in this survey web app.The data for the survey is taken from the database and the percentage of every attribute is calculated and then fed to template.For calculating that the time complexity is O(mn),if there are m persons and n attribute values.For this task you can modify the structure of the database.You have to bring the time complexity to O(mlog(n)).

### Details
This web application is in django. It also uses javascript library jquery. 

### Issue requirements / progress
- [ ] Task 1.
- [ ] Task 2.

### Resources
Django tutorial series:
https://www.youtube.com/watch?v=qgGIqRFvFFk&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK
Binary Search:
https://www.geeksforgeeks.org/binary-search/

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
