### ISSUE TITLE
Regression algorithms on gender voice,insurance datasets.

### ISSUE THREAD

**Issue by bhanutejabt** [WebClub-NITK/Hacktoberfest-2k19#277]
### Description
Implement the regression algorithms on the data sets to produce the classification metrics as an output.

### Details
- Technical Specifications: 
  - Require the concept of Linear,Logistic,Naive Bayes Regression methods
  - Python packages like pandas,sklearn etc.
- Type of issue: [Single] 

### Issue requirements / progress
- [ ] Get the classification metrics like confusion matrix,mean square errors etc.
- [ ] Predict the errors and plot the roc-curves.

### Resources
https://www.geeksforgeeks.org/types-of-regression-techniques/
https://towardsdatascience.com/machine-learning-simple-linear-regression-with-python-f04ecfdadc13

### Directory Structure
Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

**Comment by bhanutejabt** [comment]
https://github.com/WebClub-NITK/Hacktoberfest-2k19/pull/253 PR 
this resolves the issue that

**Comment by kampaitees** [comment]
I'm doing this

**Comment by bhanutejabt** [comment]
@kampaitees Actually i have done this in this PR https://github.com/WebClub-NITK/Hacktoberfest-2k19/pull/253

If you could do that is different from that PR you can start on this issue.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
