### ISSUE TITLE
Huffman Encoding of given text file

### ISSUE THREAD

**Issue by yogesh1905** [WebClub-NITK/Hacktoberfest-2k19#28]
### Description
This folder contains a text file. Write a program to Implement Huffman encoding while taking input from the text file and output the encoding  for each character.

### Details
- Technical Specifications: preferred languages are C/C++/Python.
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Implement the above mentioned algorithm efficiently.

### Resources
https://www.geeksforgeeks.org/huffman-coding-greedy-algo-3/
https://en.wikipedia.org/wiki/Huffman_coding

### Directory Structure
Create a folder named '28'(28 as in the issue number) in 'algorithms' folder. Name your program file as 'huffman.cpp' or 'huffman.c' or 'huffman.py' accordingly. Add this program file to the folder '/algorithms/28'.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @yogesh1905
Doubts and clarifications are welcome.

**Comment by waterfl0w** [comment]
I would like to claim this. :)

**Comment by FantassyLoop** [comment]
I want to take this issue

**Comment by Shuddhatm22** [comment]
i want to take up this issue

**Comment by yogesh1905** [comment]
Sure @Shuddhatm22, you can take it. Remember to send a PR before 04/10, 11:59pm.

**Comment by yogesh1905** [comment]
@SaurabhAgarwala  you can merge the PR #175
