### ISSUE TITLE
Implement a program to efficiently evaluate exponent of a given number

### ISSUE THREAD

**Issue by yogesh1905** [WebClub-NITK/Hacktoberfest-2k19#29]
### Description
Write a program that takes 3 numbers, a, b and m as input and evaluates (a^b)%m efficiently and outputs the result.

### Details
- Technical Specifications: preferred languages are C/C++/Python.
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Implement the above mentioned algorithm efficiently.

### Resources
https://www.geeksforgeeks.org/modular-exponentiation-power-in-modular-arithmetic/
https://www.hackerearth.com/practice/math/number-theory/basic-number-theory-1/tutorial/

### Directory Structure
Create a folder named '29'(29 as in the issue number) in 'algorithms' folder. Name your program file as 'fexpo.cpp' or 'fexpo.c' or 'fexpo.py' accordingly. Add this program file to the folder '/algorithms/29'.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @yogesh1905
Doubts and clarifications are welcome.

**Comment by riaaniru2613** [comment]
@yogesh1905 i want to work on this issue

**Comment by yogesh1905** [comment]
Sure @riaaniru2613, go ahead with it. Submit a PR before 03/10, 11.59pm.

**Comment by predator4hack** [comment]
I can work on this project

**Comment by riaaniru2613** [comment]
@yogesh1905 @SaurabhAgarwala I've made the changes .. please check it again

**Comment by riaaniru2613** [comment]
@yogesh1905  i've added the parenthesis in the new commit .. please review it

**Comment by yogesh1905** [comment]
I didn't find the change. So could you just re verify it :)

**Comment by yogesh1905** [comment]
You can ask any doubts if you have

**Comment by Janmansh** [comment]
@yogesh1905 I would like to work on this.

**Comment by Janmansh** [comment]
@yogesh1905 Please review PR. Thank You.

**Comment by GuptaNCode** [comment]
I want to work on that

**Comment by Himanshu307** [comment]
I would like to work on it.

**Comment by Himanshu307** [comment]
@yogesh1905 Please review my PR.

**Comment by yogesh1905** [comment]
@SaurabhAgarwala you can merge the PR #227

**Comment by yogesh1905** [comment]
@predator4hack follow the directory structure as mentioned in the issue. You are supposed to make program inside algorithms/29 directory.

**Comment by mnityesh28** [comment]
I want to work on this @yogesh1905

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by SaurabhAgarwala** [comment]
@yogesh1905 Please look into this issue

**Comment by Shahbaz90** [comment]
I want to work on this topic

**Comment by ArquiteturaJoel** [comment]
I want to work on this topic too

**Comment by ArquiteturaJoel** [comment]
@yogesh1905  please, review my PR for this issue #29
My PR
add expression in python #304

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
