### ISSUE TITLE
Barebones TCP echo server

### ISSUE THREAD

**Issue by rohit-mp** [WebClub-NITK/Hacktoberfest-2k19#3]
### Description
Implement a [bare bones](https://www.dictionary.com/browse/barebones) version of a TCP echo server in C. You can have a look at the provided resources for a detailed implementation and explanation of the same.
### Details
- Technical Specifications: Implementation is expected in C language
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Bare bones implementation
- [ ] Compiles and run as expected
- [ ] Can connect to server using `netcat` or `telnet`

### Resources
- https://www.geeksforgeeks.org/socket-programming-cc/

### Directory Structure
Create a folder named 'tcpEchoServer' under systems and name the file as 'bareboneTcpEchoServer.c' in the folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @rohit-mp
Doubts and clarifications are welcome.

**Comment by NJnisarg** [comment]
Can you please mention where can I place the files in the repo?

**Comment by rohit-mp** [comment]
> Can you please mention where can I place the files in the repo?

Create a folder named 'tcpEchoServer' under systems and name the file as 'bareboneTcpEchoServer.c' in the folder.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
