### ISSUE TITLE
Convert TCP Socket program to UDP program

### ISSUE THREAD

**Issue by kampaitees** [WebClub-NITK/Hacktoberfest-2k19#30]
### Description
From [here](https://github.com/kampaitees/Ethical-Hacking-Basic-using-Socket-Programming/tree/master/Basic%20programs%20of%20Socket%20Programming/Chat%20application) you can get the code of Client and Server implemented in python for TCP protocol.
You have to convert it to UDP protocol(unreliable connectionless transport layer protocol). 

### Details
- Technical Specifications: Python, Understanding of Transport layer protocols and Client-Server 
                                           Architecture
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
-  Implement the above-mentioned algorithm efficiently.
- This code is a chat application in TCP so don't just copy-paste the UDP architecture you have 
   to modify that too. 

### Resources
- [Client-Server Architechture](https://www.w3schools.in/what-is-client-server-architecture/)
- [TCP & UDP](https://en.wikibooks.org/wiki/Communication_Networks/TCP_and_UDP_Protocols)
- [Sockets in python](https://www.geeksforgeeks.org/socket-programming-python/#targetText=Socket%20Programming%20in%20Python,reaches%20out%20to%20the%20server.)
- [UDP in python](https://pythontic.com/modules/socket/udp-client-server-example#targetText=UDP%20is%20the%20abbreviation%20of,server%20also%20runs%20on%20UDP.)
- [TCP in python](https://gist.github.com/Integralist/3f004c3594bbf8431c15ed6db15809ae)

### Directory Structure
Create a new folder called "Sockets" inside the development folder and add all the code corresponding to this issue inside /development/Sockets.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further issues, feel free to contact me @kampaitees any time. Requests for review are welcomed. Happy Learning!

**Comment by brendanAlbert** [comment]
I'd like to handle this one :)

**Comment by NJnisarg** [comment]
Good work @brendanAlbert! Closing the issue now.
