### ISSUE TITLE
Reduced row echelon form of a matrix

### ISSUE THREAD

**Issue by pattarvarun** [WebClub-NITK/Hacktoberfest-2k19#31]
### Description
Write a C program to get the reduced row echelon form of a matrix.

### Details
- Technical Specifications: Implementation is expected in C.
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Efficient algorithm Implementation

### Resources
https://en.wikipedia.org/wiki/Row_echelon_form

### Directory Structure
Create a directory named 'ReducedRowEchelonForm' under Algorithms and name the file as reducedRowEchelonForm.c

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @pattarvarun
Doubts and clarifications are welcome.

**Comment by KeertiCh** [comment]
I would like to work on this

**Comment by predator4hack** [comment]
I would like to work on it

**Comment by pattarvarun** [comment]
Yeah. Go ahead.

**Comment by GuptaNCode** [comment]
i want to work on this project

**Comment by shivam-131** [comment]
Is this issue free now? I'm interested.

**Comment by ArquiteturaJoel** [comment]
I would like to work on it

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
