### ISSUE TITLE
Airfoil Noise Prediction (Regression)

### ISSUE THREAD

**Issue by nihal-rao** [WebClub-NITK/Hacktoberfest-2k19#33]
### Description
Implement any regression model to predict the self noise generated by an airfoil using various features provided.Target output is sound level in decibels.

The dataset can be found [here](https://archive.ics.uci.edu/ml/datasets/Airfoil+Self-Noise)

The given features are:

1.Frequency, in Hertzs.
2.Angle of attack, in degrees.
3.Chord length, in meters.
4.Free-stream velocity, in meters per second.
5.Suction side displacement thickness, in meters.

### Details
- Technical Specifications: python, numpy, pandas, scikit-learn
- Type of issue: Single
- Time Limit: **2 days**

### Issue requirements / progress
- [ ] Train a regression model on the first 1200 samples and report mean squared error on the remaining observations

### Resources
- To help you get started, the starter code `airfoil_noise_starter_code.ipynb` is present in `/machineLearning/33`
- Jupyter notebooks [installation](https://jupyter.org/install) 
- [Python tutorial](https://docs.python.org/3/tutorial/index.html)
- [Pandas tutorial](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html#min)
- [Introduction to regression in machine learning](https://towardsdatascience.com/introduction-to-machine-learning-algorithms-linear-regression-14c4e325882a)
- [Scikit-learn Linear Regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)
- [Scikit-learn Ridge Regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html#sklearn.linear_model.Ridge)

### Directory Structure
Add your solution file to 'machineLearning/33' folder. The path for your solution file should look like this:
`/machineLearning/33/<your_solution_file>`

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @nihal-rao
Doubts and clarifications are welcome.
**Happy Coding!**

**Comment by SaurabhAgarwala** [comment]
Closing this as PR #39 resolves it
