### ISSUE TITLE
Form validation using JavaScript

### ISSUE THREAD

**Issue by Chans321** [WebClub-NITK/Hacktoberfest-2k19#36]
### Description
Given a html code to implement a feedback form(the code can be found in `Development/Issue_36/feedback.txt`, write 2 JavaScript functions -one to validate email address and 1 to validate that the phone number is a valid 10 digit phone number with (+91) in the beginning.

### Details
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Validate email address.
- [ ] Validate phone number.

### Resources
https://www.w3schools.com/js/js_validation.asp

### Directory Structure
Make a directory called "form validation" in Development folder and place the solution file in it.

#### Note
Please claim the issue first by commenting here before starting to work on it.

Please request a review from @Chans321 after making a PR

**Comment by nirmalhk7** [comment]
This one's claimed.

**Comment by bilalbutt044** [comment]
is this still open?

**Comment by Chans321** [comment]
Yeah. Create a pr once done.

**Comment by thekazi** [comment]
Can I work on this one?

**Comment by ArquiteturaJoel** [comment]
I would like to work on it

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
