### ISSUE TITLE
Code refactoring and base conversion using recursion

### ISSUE THREAD

**Issue by Chans321** [WebClub-NITK/Hacktoberfest-2k19#37]
### Description
This issue mainly consists of 2 tasks. Your first task is to understand the program given in `algorithms/recursion/code_refactoring.c` and then modify it to adhere to good programming practices by giving meaningful variable names, spacing, indentation, comments etc. For the second part, you are required to write a program which converts(prints) a positive decimal number to its equivalent in any given base (2 <= base <= 16) using recursion. The recursive function may take the decimal number and the base as arguments. The program should adhere to good programming practices.

### Details
- Type of issue: Multiple
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Documentation of code.
- [ ] Write a program which converts(prints) a positive decimal number to its equivalent in any given base (2 <= base <= 16) using recursion. The recursive function may take the decimal number and the base as arguments..

### Resources
https://cs50.readthedocs.io/style/c/

### Directory Structure
Make a directory called "Recursion" in algorithms and place your solution files there.

#### Note
Please claim the issue first by commenting here before starting to work on it.

Request a review from @Chans321 after creating a PR.

**Comment by entowan** [comment]
Hi, can I work on this issue?
