### ISSUE TITLE
Rewriting code using a supported library

### ISSUE THREAD

**Issue by adharshkamath** [WebClub-NITK/Hacktoberfest-2k19#38]
### Description
`development/Issue_38/script.py` uses the crypt python module, which will be deprecated in Python 3.8. The task is to rewrite the code using an alternative python module.

### Details
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Should have the expected behaviour (similar to the original file)

### Resources

- https://docs.python.org/3/library/crypt.html
- https://www.python.org/dev/peps/pep-0594/

### Directory Structure
Add the new script to the original folder. The new script should be named `RewrittenScript.py`

#### Note
Please claim the issue first by commenting here before starting to work on it.

While requesting a PR, request a review from @adharshkamath.
Doubts and clarifications are welcome.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
