### ISSUE TITLE
Implement Text Search for tables in javascript

### ISSUE THREAD

**Issue by harshnitk17** [WebClub-NITK/Hacktoberfest-2k19#40]
### Description
Write JavaScript code to implement text search for html tables.It must be similar to the datatables plugin in jQuery.

### Details
- Technical Specifications: Implement a Search for tables which can dynamically change the output based on the input given in search box.No need to implement other features of Data tables,implement only search.
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Implement a basic html table.No styling required.
- [ ] Implement Text search for that table using javascript

### Resources
https://www.w3schools.com/howto/howto_js_filter_table.asp
https://datatables.net/manual/

### Directory Structure
create a folder called "TableSearch" in development folder and upload the html and js file there.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @harshnitk17

**Comment by brendanAlbert** [comment]
Hello, hello.  I would love to try and tackle this bad boy.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
