### ISSUE TITLE
Finding the strength of a given Password.

### ISSUE THREAD

**Issue by SkaMessi10** [WebClub-NITK/Hacktoberfest-2k19#41]
### Description
Click the link below for the problem statement.
[Hacktoberfest1.docx](https://github.com/WebClub-NITK/Hacktoberfest-2k19/files/3677050/Hacktoberfest1.docx)

### Details
- Technical Specifications: Can use any language like C,C++,Java,Python,etc.
- Type of issue: Single
- Time Limit: 5 hours

### Issue requirements / progress
- [ ] Should meet the requirements as per the problem statement. Program is expected to be optimized to the max.

### Resources
(1) https://www.geeksforgeeks.org/program-check-strength-password/
(2) https://www.w3resource.com/python-exercises/python-conditional-exercise-15.php

### Directory Structure
Create a directory called 'PasswordStrength' in the 'algorithms' directory and upload your program there
#### Note
Please claim the issue first by commenting here before starting to work on it.
While requesting a PR, request a review from @SkaMessi10.
Any doubts or clarifications will be cleared promptly.

**Comment by csp98** [comment]
Hi. I would like to work on this issue.

**Comment by riaaniru2613** [comment]
@SkaMessi10  i want to work on this issue

**Comment by SkaMessi10** [comment]
@SaurabhAgarwala ...Please merge the issue. The task is complete.

**Comment by DeltaCube23** [comment]
I would like to work on this

**Comment by SkaMessi10** [comment]
> I would like to work on this

Sorry,but the issue has already been solved. Please take a look at some of the other problems in the repository.
