### ISSUE TITLE
Topological sorting for Directed Acyclic Graph

### ISSUE THREAD

**Issue by harshnitk17** [WebClub-NITK/Hacktoberfest-2k19#42]
### Description
Topological sorting for Directed Acyclic Graph (DAG) is a linear ordering of vertices such that for every directed edge uv, vertex u comes before v in the ordering. Write  a program to find any topological sort of a given graph.

### Details
- Technical Specifications:Use only C,C++,Java or Python to write the code
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Write code for finding any topological sort of a DAG. The code should have a time complexity of O(V+E) where V and E are number of vertices and edges in the graph.

### Resources
https://www.geeksforgeeks.org/topological-sorting/

### Directory Structure
Make a directory called "TopologicalSort" under the algorithms folder . Upload the code under this directory.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @harshnitk17.

**Comment by Shuddhatm22** [comment]
i want to take this one

**Comment by harshnitk17** [comment]
> i want to take this one

Sure go ahead

**Comment by Shuddhatm22** [comment]
please review the issue

**Comment by Shuddhatm22** [comment]
@vishy-kothari-96 I already made a pull request 3 days ago, but they have not reviewed it yet.
