### ISSUE TITLE
Generating Prime Numbers

### ISSUE THREAD

**Issue by abhishekkumar2718** [WebClub-NITK/Hacktoberfest-2k19#44]
### Description
A prime number (or a prime) is a natural number greater than one that cannot be formed by multiplying two smaller natural numbers. Generating and verifying if a given number is prime is of critical importance in cryptography.

In this issue, you will need to generate all prime numbers between two given inputs - **low** and **high**.

Example: If the inputs are `low = 2, high = 10`, your program should return `2, 3, 5, 7`

### Details
- Technical Specifications:
  - The code can be written in any language. Please ensure proper standards and conventions are met.
  - You cannot use a non-trivial list of prime numbers from an external source.
  - The code should be run as an executable, using system arguments for input.
- Type of issue: Single
- Time Limit: One day

### Resources
- [Wikipedia article on Prime Numbers](https://en.wikipedia.org/wiki/Prime_number)
- [Wikipedia article on Generating Prime Numbers](https://en.wikipedia.org/wiki/Generation_of_primes)

### Directory Structure
- Create a folder `44_generation_of_primes` within the folder `algorithms` of this repository.
- Place all your files within this directory.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues

For review, please request @abhishekkumar2718.

**Comment by adrianoapj** [comment]
Can I work on this?

**Comment by adrianoapj** [comment]
Can I work on this?

**Comment by lryanle** [comment]
Claiming.

**Comment by anki-raj** [comment]
Claiming for an efficient solution using segmented sieve.

**Comment by jilloestreicher** [comment]
Would like to claim this project!

**Comment by NJnisarg** [comment]
There are already 2 merged requests. Closing this issue.
