### ISSUE TITLE
login script for NITK-NET

### ISSUE THREAD

**Issue by kinshukk** [WebClub-NITK/Hacktoberfest-2k19#46]
### Description
Write a script that sends a POST request to the captive portal (nac.nitk.ac.in:8090) with credentials, and logs you into the server. This can be done using the `requests` module.
To know what exactly the POST request should contain, open up the captive portal website, do 'Inspect Element', and open the 'Network' tab. Then login in the main page. You'll see the list of requests that were sent. There are options to see the request data if you right click on it.

### Details
- Technical Specifications:
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] You should be able to access the internet after the script is run.

### Resources
https://stackoverflow.com/questions/15603561/how-can-i-debug-a-http-post-in-chrome

### Directory Structure
Edit the file `development/login_script/login.py`

#### IMPORTANT
Please don't commit your login credentials along with the code! Put placeholders like Username='111111', password='greatest_password'.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Contact @kinshukk

**Comment by tharun634** [comment]
I would like to claim this issue!

**Comment by kinshukk** [comment]
@tharun634 Sure, go ahead!

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
