### ISSUE TITLE
Conway's Game of Life

### ISSUE THREAD

**Issue by kinshukk** [WebClub-NITK/Hacktoberfest-2k19#47]
### Description
You are given code that simulates the Brian's brain automation, and uses pygame.
Change the logic so that it simulates Conway's game of life instead.

### Details
- Type of issue: Single
- Time Limit: 2 days

### Resources
- https://en.wikipedia.org/wiki/Brian's_Brain
- https://en.wikipedia.org/wiki/Conway's_Game_of_Life
- https://www.pygame.org/docs/

### Directory Structure
See the file `development/GameOfLife/simulate.py`.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Contact @kinshukk

**Comment by matthewcm** [comment]
I would like to work on this. I want to improve my python coding ability

**Comment by kinshukk** [comment]
Okay go ahead
