### ISSUE TITLE
Optimize recursive Fibonacci implementation

### ISSUE THREAD

**Issue by shanthanu9** [WebClub-NITK/Hacktoberfest-2k19#48]
### Description
```algorithms/48/fib.cpp``` contains a recursive implementation for computing the nth Fibonacci number. Although the program is correct, it takes too long to compute Fibonacci numbers. For instance, it takes a very very long time (> 1 hour) to compute just the 60th Fibonacci number. Suggest an optimization to improve the performance and refractor the given program to implement the optimization.

### Details
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Suggest Optimization.
- [ ] Refractor ```fib.cpp```.

### Resources
[Computational complexity of Fibonacci sequence](https://stackoverflow.com/questions/360748/computational-complexity-of-fibonacci-sequence)

### Directory Structure
The program is in ```algorithms/48/fib.cpp```.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @shanthanu9.
Doubts and clarifications are welcome.

**Comment by shanthanu9** [comment]
Sure, go ahead!

**Comment by FantassyLoop** [comment]
please review

**Comment by ADITYA-CS** [comment]
I want to work on this.

**Comment by aansari4599** [comment]
I want to work on this.

**Comment by NegaMage** [comment]
I want to work on this. I'll try using DP.

**Comment by shanthanu9** [comment]
It's nice to see so many of you want to work on this! Although @FantassyLoop has already submitted a PR and it's under review. But he hasn't responded to my review for two days now. So if he doesn't reply to my PR review by tomorrow, I will let one of you new folks take up the issue.

**Comment by NegaMage** [comment]
I implemented a matrix exponent solution in O(n) time complexity and space complexity. PR #223 
Please review, @shanthanu9

**Comment by codebreaker-00** [comment]
I want to submit a PR. Please review
