### ISSUE TITLE
Write a shell/bash script from scratch to print out server information such as utilization, current connections, disk and memory usage, recent logins etc.

### ISSUE THREAD

**Issue by abhinavpy** [WebClub-NITK/Hacktoberfest-2k19#49]
### Description
Write a bash script that prints the server's:
1. Resource Utilization
2. Current Connections to the server.
3. Disk and Memory Usage.
4. List of recent logins.
Read through the Issue requirements below and print results exactly as the order specified.

### Details
- Technical Specifications:
- Type of issue: [Single] A single PR consisting of the bash file will do.
- Time Limit: A time limit of one day will be enforced once someone has claimed the issue. If that person hasn't submitted a PR within this limit, the issue will be assigned to the person who applied next.

### Issue requirements / progress
Write your bash script such that information is printed in the following order:
- [ ] Print information about how long your system has been running together with the current time, number of users with running sessions, and the system load averages for the past 1, 5, and 15 minutes.
- [ ] Display the list of all the users logged in and out since the file /var/log/wtmp was created.
- [ ] Print free Disk space, total disk space, free memory and total memory.
- [ ] Print the 3 most expensive processes running on the server.
- [ ] Print all open TCP ports on the server.
- [ ] Print all connections to the server. 

### Resources
Google the stuff. You'll easily find all the answers.

### Directory Structure
Create this file under the ```systems``` directory

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Issue creator : @abhinavpy
Maintainer : @SaurabhAgarwala @NJnisarg

**Comment by tarungulati1988** [comment]
Is this available? If yes I can take this up.

**Comment by abhinavpy** [comment]
Yes, you can start off with it.

**Comment by christophevolbert** [comment]
Can i still work on it ?

**Comment by abhinavpy** [comment]
@christophevolbert you can start working on it since I haven't yet seen any pull request made from @tarungulati1998 regarding this issue. Make sure you comment here once you've made a pull request so I can review before merging.

**Comment by vishy-kothari-96** [comment]
Am I allowed to work on this?

**Comment by abhinavpy** [comment]
@vishy-kothari-96 yes you can start working on it.

**Comment by vishy-kothari-96** [comment]
@abhinavpy I've made a PR. Please review.

**Comment by abhinavpy** [comment]
@vishy-kothari-96 has submitted a solution. Issue is will be closed.
