### ISSUE TITLE
Decimal to Binary Conversion

### ISSUE THREAD

**Issue by shanthanu9** [WebClub-NITK/Hacktoberfest-2k19#51]
### Description
Write a program in C to convert a user-entered decimal number to binary without using in-built functions that explicitly do it for you.

### Details
- Technical Specifications: Preferred language is C
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Implement the given task.
- [ ] Ensure that it compiles and runs as expected.

### Resources
[https://www.rapidtables.com/convert/number/decimal-to-binary.html](https://www.rapidtables.com/convert/number/decimal-to-binary.html)

### Directory Structure
Create a folder titled ```51``` in algorithms. Add the required program in ```algorithms\51``` with name ```dec2bin.c```.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @deepakkavoor.
Doubts and clarifications are welcome.

**Comment by shash137** [comment]
Hello, I can write the C program for decimal to binary converter.  I wan to claim this issue.

**Comment by deepakkavoor** [comment]
Go ahead @shash137

**Comment by shash137** [comment]
Hey @deepakkavoor i have submitted my PR for review, I've one doubt that it's issue no. 51 but in the description it says to make a folder of 52. I have done accordingly, please check it. 
Thank you.

**Comment by shanthanu9** [comment]
Sorry my bad. It should folder 51 itself. I have updated the issue accordingly

**Comment by shash137** [comment]
@shanthanu9 do i need to change the folder name, because i have generated PR already

**Comment by shanthanu9** [comment]
Yeah change the folder name. Just change the folder name and push the
changes. It will be automatically reflected in the PR.

**Comment by shash137** [comment]
@shanthanu9 I have made a PR in Master branch, so i think folder name can't be renamed.

**Comment by shash137** [comment]
@shanthanu9 done

**Comment by BlazkowiczTon** [comment]
Can I work on it.

**Comment by deepakkavoor** [comment]
You can implement in any language other than c and c++

**Comment by NJnisarg** [comment]
The first PR has been merged. Closing the issue.
