### ISSUE TITLE
Lucas sequence using Recursion

### ISSUE THREAD

**Issue by shanthanu9** [WebClub-NITK/Hacktoberfest-2k19#52]
### Description
Write a program in C to generate the Lucas number desired by the user using the concept of recursion.

### Details
- Technical Specifications: Preferred language is C.
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Implement the given task.
- [ ] Ensure that is compiles and runs as expected.

### Resources
[https://en.wikipedia.org/wiki/Lucas_number](https://en.wikipedia.org/wiki/Lucas_number)

### Directory Structure
Create a folder titled ```52``` in algorithms. Add the required program in ```algorithms\52``` with name ```lucas.c```.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @deepakkavoor.
Doubts and clarifications are welcome.

**Comment by Rhuancpq** [comment]
Working on it

**Comment by deepakkavoor** [comment]
Sure

**Comment by deepakkavoor** [comment]
@Rhuancpq this looks fine. 
@SaurabhAgarwala please merge this PR.
