### ISSUE TITLE
Snake Game - Code Snippet

### ISSUE THREAD

**Issue by SakshatRao** [WebClub-NITK/Hacktoberfest-2k19#53]
### Description
Create a snippet of code to terminate a basic snake game when the snake touches itself.
(P.S. - This snippet must be added to the existing snake game code. It will be present in the algorithms/Issue_53 folder. Sorry about the confusion!)

### Details
- Technical Specifications: Javascript is preferred
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Javascript

### Directory Structure
Create a folder called 'Issue_53' in the 'algorithms' directory. Add the required program in algorithms/Issue_53.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @ameyanrd or @SakshatRao.
Doubts and clarifications are welcome.

**Comment by vaibhav111tandon** [comment]
i can take this issue.

**Comment by ameyanrd** [comment]
Hi! so you can work on the issue. I see your code, but we want you to work on the game we have. We'll soon upload it in ```algorithms/53``` directory. Try to understand the code from the comments and try to add the termination condition at commented places. For any clarifications/doubts, feel free to ask here. All the best!

**Comment by iron-bergh** [comment]
Hi! is the issue free now?

**Comment by SakshatRao** [comment]
> Hi! is the issue free now?

In case we do not receive any submission by **tonight 9 PM** from the previous participant, you can take up this issue...

**Comment by MerlijnVH** [comment]
I haven't seen any activity in a while, can I take a look?

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
