### ISSUE TITLE
Add synchronisation mechanisms to avoid race condition.

### ISSUE THREAD

**Issue by Madhuparna04** [WebClub-NITK/Hacktoberfest-2k19#55]
### Description
In file synchronization.c 10 threads add a value of 10,000 to the global variable sum. But because of race condition, the final value of sum is not 1,00,000.
Add appropriate synchronization constructs so that the value stored in sum is deterministic and equal to 1,00,000.

### Details
- Technical Specifications:
- Type of issue: Multiple
- Time Limit: 2 days

### Resources
- Wikipedia: [Synchronization](https://en.wikipedia.org/wiki/Synchronization_(computer_science))
- Pthreads: [POSIX thread library.](https://www.cs.cmu.edu/afs/cs/academic/class/15492-f07/www/pthreads.html)

### Directory Structure
- Create a folder called 'synchronization' in the 'algorithms' directory. Add the required program in algorithms\synchronization.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @Madhuparna04.

**Comment by David-Hinschberger** [comment]
I can work on this.

**Comment by Madhuparna04** [comment]
Hi, @David-Hinschberger thank you for working on this issue.
@SaurabhAgarwala I have verified the PR, please proceed with merging the Pull request.

**Comment by NJnisarg** [comment]
@Madhuparna04 @David-Hinschberger I have merged the PR. Closing the issue now.
