### ISSUE TITLE
Finding the nth largest number in O(n)

### ISSUE THREAD

**Issue by NKH123** [WebClub-NITK/Hacktoberfest-2k19#56]
### Description
Write a program in C to find the the kth largest number in an unsorted array in linear time using Median of Median algorithm.

### Details
- Technical Specifications: Preferred language is C
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Implement the given task.
- [ ] Ensure that it runs in linear time.
- [ ] Ensure that is compiles and runs as expected..

### Resources
https://brilliant.org/wiki/median-finding-algorithm/

### Directory Structure
Create a folder named '56'(56 as in the issue number) in 'algorithms' folder. Name your program file as 'k_largest.c'. Add this program file to the folder '/algorithms/56'.
#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Please mention yourself as the point of contact so that the person submitting the PR can request review from @NKH123.
Doubts and clarifications are welcome.

**Comment by benknoble** [comment]
I'll claim this one.

How do we *ensure that it runs in linear time*? Just implement the algorithm, or are you looking for proofs, or something "good enough"?

**Comment by bigBrain1901** [comment]
@NKH123 Please review this code and merge if alright

**Comment by NKH123** [comment]
@benknoble Sure. I'll assign you the issue. Just implementing the MoM algorithm is fine. No proofs required.
You have till 24 hrs to send a PR.

**Comment by NKH123** [comment]
> @NKH123 Please review my code and merge if alright
I have reviewed your code and made comments.

**Comment by bigBrain1901** [comment]
I don't know what the MoM algorithm is, but I will look it up and send a PR

**Comment by nandakishore323** [comment]
is this still open?

**Comment by benknoble** [comment]
@nandakishore323 I believe we're just waiting on #148 to merge and close it
