### ISSUE TITLE
Implement Insertion Sort

### ISSUE THREAD

**Issue by SaurabhAgarwala** [WebClub-NITK/Hacktoberfest-2k19#60]
### Description
Implement the Insertion Sort Algorithm in any language of your choice

### Details
- Technical Specifications:
- Type of issue: Single
- Time Limit: ~24 hours after claiming the issue
### Issue requirements / progress
- [ ] Implement the insertion sort algorithm in any language of your choice
- [ ] Properly document the code implemented.

### Resources
[Insertion Sort-Wikipedia](https://en.wikipedia.org/wiki/Insertion_sort)

### Directory Structure
Please make a directory with name as `60-Insertion Sort` under the `algorithms` directory of the main repo. In this directory, add your file named as `insertion_sort.c` or `insertion_sort.py` or with whatever extension you require. So the final structure will be `algorithms/60-Insertion Sort/insertion_sort.**`.

#### Note
Please claim the issue first by commenting here before starting to work on it.

When you have added the relevant files and made the PR, please request a review from @SaurabhAgarwala

**Comment by TobyAsE** [comment]
I'm on it.

**Comment by SaurabhAgarwala** [comment]
Sure. Please send a PR by 23:59 IST, 02/10/2019.

**Comment by 4molybdenum2** [comment]
can i send a pr?

**Comment by SaurabhAgarwala** [comment]
> can i send a pr?

@4molybdenum2 Sorry, the issue has already been taken up. If a PR is not send within the given deadline, you will be asssigned next.

**Comment by bamsarts** [comment]
i'm on it using php

**Comment by datbnt-0905** [comment]
i'm on it using C++

**Comment by myselfronin** [comment]
I'm on it using Java

**Comment by whilson03** [comment]
I am working on it with python

**Comment by Subho13** [comment]
Can I do it in C?

**Comment by DeltaCube23** [comment]
Can I still try it on C++ ?

**Comment by whilson03** [comment]
I think you should

**Comment by NJnisarg** [comment]
There have already been 3 merged PR. Closing the issue now
