### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by SaurabhAgarwala** [WebClub-NITK/Hacktoberfest-2k19#63]
### Description
Create a simple HTML form of your own choice having various input fields ans then store the data entered in the form into a external database.

### Details
- Technical Specifications: Can use any available Libraries/Frameworks for the task
- Type of issue: Single 
- Time Limit: ~48 hours after claiming the issue

### Issue requirements / progress
- [ ] Create an HTML form with atleast 5 input options.
- [ ] Storing the data taken from the form into a database of own choice. (Eg: MySQL, Firebase, MongoDB).
- [ ] Create a README to explain the work done.

### Resources
- [Creating an HTML form](https://www.w3schools.com/html/html_forms.asp)
- [Connecting Firebase to a form](https://www.youtube.com/watch?v=PP4Tr0l08NE&t=1358s)

### Directory Structure
Create a folder named `63-DatabaseIntegration` under the `systems` folder of the main repo. Add the relevant files under this folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.

When you have added the relevant files and made the PR, please request a review from @SaurabhAgarwala

**Comment by adityagamer786** [comment]
I would like to work on this

**Comment by adityagamer786** [comment]
@SaurabhAgarwala please review my code
