### ISSUE TITLE
Recycler view implementation

### ISSUE THREAD

**Issue by shrinidhi99** [WebClub-NITK/Hacktoberfest-2k19#67]
### Description
The recycler view implemented in java and kotlin do not match

### Details
The kotlin recycler view looks like the simplest way of implementing recycler view but the java version implements recycler view along with searching in a recycler view.
### Issue requirements / progress
- [x] Remove the search in java recycler view

### Resources
recycler view in android documentation

### Directory Structure
development/recyclerViewTemplate/Java
#### Note
@shrinidhi99  will take up the issue and resolve it.
#### For co-ordinators/maintainers creating the issues
@shrinidhi99 needs to be requested for any changes in the code further.

@SaurabhAgarwala @NJnisarg can you add hacktoberfest tag to this new issue?

**Comment by shrinidhi99** [comment]
I have made a PR to resolve this issue. Who needs to close this?

**Comment by shrinidhi99** [comment]
Can someone review it? @harshnitk17 @SaurabhAgarwala

**Comment by NJnisarg** [comment]
Merged it. Closing the issue
