### ISSUE TITLE
Target Sum from 2 BSTs

### ISSUE THREAD

**Issue by SrivatsanV** [WebClub-NITK/Hacktoberfest-2k19#7]
### Description
Come up with an efficient algorithm for finding two numbers, a and b from 2 given binary search trees such that a+ b = S (Target Sum) and a & b are not from the same BST.

### Details
- Technical Specifications: Preferable languages are C/C++
- Type of issue: Single
- Time Limit: 1 day.

### Issue requirements / progress
- [ ] Efficient algorithm implementation.

### Resources
 - https://www.geeksforgeeks.org/binary-search-tree-data-structure/
 - https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/

### Directory Structure
Create a folder named '7'(7 as in the issue number) in 'algorithms' folder. Name your program file as 'target-sum-bst.cpp' or 'target-sum-bst.c' accordingly. Add this program file to the folder '/algorithms/7'.

#### Note
Please claim the issue first by commenting here before starting to work on it.
While submitting a PR, request a review from @SrivatsanV
Doubts and clarifications are welcome.

**Comment by Shuddhatm22** [comment]
i am taking this issue

**Comment by Mksiyak** [comment]
i would like to work on it.

is root pointer will be given for both trees and data only(if data then sorted or not)?

and if i got two numbers one from each tree, and they both are also present any of these two trees.
so this pair will considered as answer or not ?

**Comment by SrivatsanV** [comment]
Clarifications : 
 - Take input from the user and build a BST using linked lists (data can be in random order) 
 - Yeah the pair can be the answer, also if you find two or more pairs that follow the target sum condition, you can give any one the pairs as output.

@Shuddhatm22 - status on this issue?

**Comment by ArquiteturaJoel** [comment]
I would like to work on it
