### ISSUE TITLE
Maximum subarray sum

### ISSUE THREAD

**Issue by Sagnik-Ghosh** [WebClub-NITK/Hacktoberfest-2k19#72]
### Description
Write a program in c to find maximum subarray sum in linear time.
### Details
- Technical Specifications: language is C
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Implement the given task.
- [ ] Ensure that it runs in linear time.

### Directory Structure
Create a folder named "72" after the issue number in 'algorithms' folder. Name your program as
'maximum_subarray_sum.c'. Add this program file to the folder you created in algorithms.
#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Person submitting the PR can request review from @Sagnik-Ghosh or @narayanpai1

**Comment by HelioStrike** [comment]
I'll start working on this

**Comment by narayanpai1** [comment]
Sure. Go on!

**Comment by Sagnik-Ghosh** [comment]
Hey! @HelioStrike has already completed the task. I am closing this issue.

**Comment by Sagnik-Ghosh** [comment]
@SaurabhAgarwala please merge PR #83
