### ISSUE TITLE
Tic-tac-toe BOT

### ISSUE THREAD

**Issue by niranjanrao1509** [WebClub-NITK/Hacktoberfest-2k19#73]
### Description
Create a basic Tic-Tac-Toe implementation using minimax pruning

### Details
- Technical Specifications:
- Type of issue: [Single | Multiple] (A particular issue may have many subtasks or a possibity of different implementations, so won't be fulfilled by a single PR).
- Time Limit: 2days

### Issue requirements / progress
- [ ] Incorporate pygame for graphical UI
- [ ] Implement Alpha Beta Pruning to improve perfomance

### Resources
List of resources that might be required / helpful.
https://www.geeksforgeeks.org/minimax-algorithm-in-game-theory-set-3-tic-tac-toe-ai-finding-optimal-move/
https://www.youtube.com/watch?v=GKI3Xf65Plw

Make sure a directory is created under the corresponding domain folder properly following the collaborator guidelines and mention it here.

#### Note
Please claim the issue first by commenting here before starting to work on it.

Contact Niranjan Rao for any help(niranjanrao1509@gmail.com

**Comment by lelloman** [comment]
Hi, can I pick this up for hacktoberfest? I have no idea what's minmax pruning so it sounds like an interesting one :)

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
