### ISSUE TITLE
segmentation fault in merge sort

### ISSUE THREAD

**Issue by Sagnik-Ghosh** [WebClub-NITK/Hacktoberfest-2k19#74]
### Description
Debug the encountered segmentation fault in merge sort algorithm
### Details
- Technical Specifications: language C
- Type of issue: Single
- Time Limit: 1 day

### Issue requirements / progress
- [ ] Debug the merge sort code

### Directory Structure
The program is in algorithms/74/source.c

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
Person submitting the PR can request review from @Sagnik-Ghosh or @narayanpai1

**Comment by dipanshu231099** [comment]
i would like to correct the fault

**Comment by Sagnik-Ghosh** [comment]
> i would like to correct the fault

Sure. Please send a PR by 23:59 IST, 02/10/2019.

**Comment by dipanshu231099** [comment]
@Sagnik-Ghosh kindly review

**Comment by Sagnik-Ghosh** [comment]
@SaurabhAgarwala please merge #77. The task is complete.
