### ISSUE TITLE
Blog website complete with authentication

### ISSUE THREAD

**Issue by 17aakashsingh1999** [WebClub-NITK/Hacktoberfest-2k19#8]
### Description
Implement a website that allows you to post blogs with working authentication.

### Details
- Technical Specifications: Use any framework of your choice to implement the web app.
- Type of issue: Single
- Time Limit: 1 week

### Issue requirements / progress
- [x] Decide upon a framework- django, expressjs, flask, etc and bootstrap the project
- [x] Create the basic structure of the web site
- [x] Add functionality to the website
- [x] Add authentication system to the website
- [x] Add styling to the website

### Resources
- [Django tutorials](https://docs.djangoproject.com/en/2.2/intro/tutorial01/)

### Directory Structure
This project lives inside the development folder. Inside the development folder create a new folder called '8' (corresponding to this issue with this issue's number) and put all the files for the project inside '/development/8/'.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For and further clarification on this project, you can contact me, @17aakashsingh1999 and also request a review from me on submitting a PR!

**Comment by dbarrerap** [comment]
I'll start working on this!

**Comment by 17aakashsingh1999** [comment]
> I'll start working on this!

@dbarrerap go ahead!

**Comment by dbarrerap** [comment]
Creating PR

**Comment by dbarrerap** [comment]
Request for review @17aakashsingh1999

**Comment by 17aakashsingh1999** [comment]
@dbarrerap great work!!
@SaurabhAgarwala please merge this PR.

**Comment by dbarrerap** [comment]
Thanks!

**Comment by NJnisarg** [comment]
Closing the Issue. Merged the referenced PR
