### ISSUE TITLE
AES-CBC using ECB mode

### ISSUE THREAD

**Issue by deepakkavoor** [WebClub-NITK/Hacktoberfest-2k19#87]
### Description
Write a Python program to implement AES encryption and decryption in CBC mode. Refer to the PyCrypto package. You need to use the ```Crypto.Cipher.AES``` module in ```AES.MODE_ECB``` to chain ciphertext blocks when implementing CBC mode. **Do not use** ```AES.MODE_CBC``` **directly**.

Use the PCKS#7 padding wherever necessary.

### Details
- Technical Specifications: Language of implementation is Python.
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements / progress
- [ ] Implement CBC mode encryption
- [ ] Implement CBC mode decryption
- [ ] Choose a random Initialization Vector and a random key (using the ```Crypto.Random``` module), and print the encryption of ```"Hacktoberfest"``` (encoded in bytes). 
- [ ] Test that decrypting the above result using the same key and IV results back in ```"Hacktoberfest"``` along with the appropriate padding.

### Resources
[PyCrypto](https://www.dlitz.net/software/pycrypto/api/current/) - cryptographic package for Python

[PKCS#7](https://en.wikipedia.org/wiki/Padding_(cryptography)) padding

[Block cipher modes](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation) of operation (read about the ECB and CBC modes)

### Directory Structure
Create a folder in the ```systems``` directory corresponding to this issue number (87). Add the file ```cbc.py``` in ```systems/87``` folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.
When submitting a PR, request a review from **@deepakkavoor**.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
