### ISSUE TITLE
Automation of Sophos login in NITK

### ISSUE THREAD

**Issue by rohit-mp** [WebClub-NITK/Hacktoberfest-2k19#89]
### Description
Write a script or a tool to automate the process of sophos login connect to NITK-NET. Any approach is welcome and no fixed way of doing this expected.

### Details
- Technical Specifications: Anything which makes it simpler than manually logging in everytime
- Type of issue: Single
- Time Limit: 3 days

### Issue requirements / progress
- [ ] Script to login

### Directory Structure
Create a folder named 'sophosLogin' under systems and put all necessary files in the folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.
For any queries, tag @rohit-mp. Request a review from @rohit-mp while submitting the pull request.

**Comment by tharun634** [comment]
I would like to claim this issue and work on it!

**Comment by rohit-mp** [comment]
Sure! Go ahead.

**Comment by Mksiyak** [comment]
i would like to make executable shell script for this issue with the help of curl(tool to send get and post request through terminal).

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
