### ISSUE TITLE
An interpreter for brainfuck written in C language

### ISSUE THREAD

**Issue by 17aakashsingh1999** [WebClub-NITK/Hacktoberfest-2k19#9]
### Description
Write an interpreter for Brainfuck in C language.

### Details
- Type of issue: Single
- Time Limit: 1 week

### Issue requirements / progress
- [ ] Solve the balanced parenthesis problem - given a sequence of parenthesis find if the sequence is valid or not
- [ ] Use the knowledge of the above problem to write an interpreter
- [ ] Add logic to check if the given Brainfuck code is correct and report the error.
- [ ] Add logic to detect comments in code and ignore them.

### Resources
- [Brainfuck](https://esolangs.org/wiki/Brainfuck)
- [Balanced Parenthesis Problem](https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/)

### Directory Structure
Create a new folder called "9" inside the systems folder and add all the code corresponding to this issue inside /systems/9.

#### Note
Please claim the issue first by commenting here before starting to work on it.

#### For co-ordinators/maintainers creating the issues
For any further clarification on this issue, you are free to contact me, @17aakashsingh1999 and also you can drop me a request for review! Happy learning!

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
