### ISSUE TITLE
MultiSig Wallet Using Smart Contracts

### ISSUE THREAD

**Issue by ArnavNair** [WebClub-NITK/Hacktoberfest-2k19#92]
### Description
Design a Smart Contract using Solidity that implements a multi-sig wallet. The wallet must have functionality to have multiple users, add or remove users, and accept or withdraw funds provided at least 50% of the users agree.

### Details
- Technical Specifications: Language of implementation must be Solidity.
- Type of issue: Single
- Time Limit: 3 days

### Issue requirements / progress
- Functionality to add and remove users.
- Functionality to accept or withdraw funds, provided at least 50% of the users agree.

### Resources
Basics of Blockchain: https://blockgeeks.com/guides/what-is-blockchain-technology/
Understanding Smart Contracts: https://blockgeeks.com/guides/smart-contracts/
Solidity Tutorial: https://www.edureka.co/blog/solidity-tutorial/

### Directory Structure
Create a folder in the `systems` directory corresponding to this issue number(92). Add the file `wallet.sol` in `systems/92` folder.

#### Note
Please claim the issue first by commenting here before starting to work on it.
When submitting a PR, first request a review from @ArnavNair

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Closing the issue.
